### ISSUE TITLE
Error after checking cookies

### ISSUE THREAD

**Issue by alexanderajju** [mxrch/GHunt#103]
Traceback (most recent call last):
  File "check_and_gen.py", line 126, in <module>
    auth_token, hangouts_token = get_hangouts_tokens(cookies, driverpath)
  File "check_and_gen.py", line 61, in get_hangouts_tokens
    driver = webdriver.Chrome(
  File "/usr/local/lib/python3.8/dist-packages/seleniumwire/webdriver/browser.py", line 86, in _init_
    super()._init_(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/chrome/webdriver.py", line 73, in _init_
    self.service.start()
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/common/service.py", line 98, in start
    self.assert_process_still_running()
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/common/service.py", line 109, in assert_process_still_running
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: Service /opt/GHunt/chromedriver_linux64.zip unexpectedly exited. Status code was:

**Comment by NikolozCh** [comment]
Please check Issue #94 . I assume that you have the same problem, you need to install `ChromeDriver` first, before you start using GHunt
