### ISSUE TITLE
Unable to set chromedriver

### ISSUE THREAD

**Issue by user-setting** [mxrch/GHunt#110]
I solved the problem with check_and_gen.py which was the same issue .
now i am getting the error below:

Traceback (most recent call last):
  File "hunt.py", line 114, in <module>
    gpics(gaiaID, client, cookies, config.headers, config.regexs["albums"], config.regexs["photos"],
  File "/root/GHunt/lib/photos.py", line 104, in gpics
    out = get_source(gaiaID, client, cookies, headers, headless)
  File "/root/GHunt/lib/photos.py", line 46, in get_source
    driver = webdriver.Chrome(executable_path=driverpath, seleniumwire_options=options, options=chrome_options)
  File "/usr/local/lib/python3.8/dist-packages/seleniumwire/webdriver/browser.py", line 86, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/chrome/webdriver.py", line 95, in __init__
    RemoteWebDriver.__init__(
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 152, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 249, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 318, in execute
    self.error_handler.check_response(response)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 83

Can someone help how do i solve this error. I am using kali linux

**Comment by Sneomy** [comment]
Hi! Install please actually chromedriver(version of chromedriver should == version of your chrome)

**Comment by user-setting** [comment]
I was able to solve it with the help of #61
