### ISSUE TITLE
After checking cookies Error

### ISSUE THREAD

**Issue by Lorenz11x** [mxrch/GHunt#112]
Hi Boss, I'm this problem after checking coockies, please you can help me? Tanks !!

[+] The cookies seems valid! Generating the Google Docs and Hangouts token...

Google Docs Token => XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX:XXXXXXX
Traceback (most recent call last):
  File "check_and_gen.py", line 126, in <module>
    auth_token, hangouts_token = get_hangouts_tokens(cookies, driverpath)
  File "check_and_gen.py", line 61, in get_hangouts_tokens
    driver = webdriver.Chrome(
  File "/usr/local/lib/python3.8/dist-packages/seleniumwire/webdriver/browser.py", line 86, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/chrome/webdriver.py", line 76, in __init__
    RemoteWebDriver.__init__(
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 87
Current browser version is XX.XX.X.XX.XX with binary path /usr/bin/google-chrome

**Comment by Lorenz11x** [comment]
Sorry ... I had downloaded the updated version of the chrome driver, this was the problem, solved !!

**Comment by HenkPoley** [comment]
You can also download the most recent / matching ChromeDriver and drop it in GHunt/<Chrome version>/
