### ISSUE TITLE
httpx.ReadTimeout: The read operation timed out

### ISSUE THREAD

**Issue by presmedia002** [mxrch/GHunt#119]
Activated Google services :
- Youtube
- Kaboo
- Photos
- Maps
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/httpx/_exceptions.py", line 326, in map_exceptions
    yield
  File "/usr/local/lib/python3.8/dist-packages/httpx/_client.py", line 861, in _send_single_request
    (status_code, headers, stream, ext) = transport.request(
  File "/usr/local/lib/python3.8/dist-packages/httpcore/_sync/connection_pool.py", line 200, in request
    response = connection.request(
  File "/usr/local/lib/python3.8/dist-packages/httpcore/_sync/connection.py", line 100, in request
    return self.connection.request(method, url, headers, stream, ext)
  File "/usr/local/lib/python3.8/dist-packages/httpcore/_sync/http11.py", line 72, in request
    ) = self._receive_response(timeout)
  File "/usr/local/lib/python3.8/dist-packages/httpcore/_sync/http11.py", line 133, in _receive_response
    event = self._receive_event(timeout)
  File "/usr/local/lib/python3.8/dist-packages/httpcore/_sync/http11.py", line 172, in _receive_event
    data = self.socket.read(self.READ_NUM_BYTES, timeout)
  File "/usr/local/lib/python3.8/dist-packages/httpcore/_backends/sync.py", line 62, in read
    return self.sock.recv(n)
  File "/usr/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.8/dist-packages/httpcore/_exceptions.py", line 12, in map_exceptions
    raise to_exc(exc) from None
httpcore.ReadTimeout: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "hunt.py", line 102, in <module>
    data = ytb.get_channels(client, name, cfg)
  File "/root/GHunt/lib/youtube.py", line 72, in get_channels
    from_youtube = youtube_channel_search(client, query)
  File "/root/GHunt/lib/youtube.py", line 34, in youtube_channel_search
    req = client.get(avatar_link)
  File "/usr/local/lib/python3.8/dist-packages/httpx/_client.py", line 907, in get
    return self.request(
  File "/usr/local/lib/python3.8/dist-packages/httpx/_client.py", line 733, in request
    return self.send(
  File "/usr/local/lib/python3.8/dist-packages/httpx/_client.py", line 767, in send
    response = self._send_handling_auth(
  File "/usr/local/lib/python3.8/dist-packages/httpx/_client.py", line 805, in _send_handling_auth
    response = self._send_handling_redirects(
  File "/usr/local/lib/python3.8/dist-packages/httpx/_client.py", line 837, in _send_handling_redirects
    response = self._send_single_request(request, timeout)
  File "/usr/local/lib/python3.8/dist-packages/httpx/_client.py", line 861, in _send_single_request
    (status_code, headers, stream, ext) = transport.request(
  File "/usr/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.8/dist-packages/httpx/_exceptions.py", line 343, in map_exceptions
    raise mapped_exc(message, **kwargs) from exc  # type: ignore
httpx.ReadTimeout: The read operation timed out

**Comment by mxrch** [comment]
Hello @presmedia002, does this issue persist today ?

**Comment by niIeshkumar** [comment]
hey @mxrch, this issue is still present. 
the first 2 emails ran successfully for me, but this ReadTimeout exception happens on the 3rd and 4th emails while checking Maps service

**Comment by nancyrathore92** [comment]
i got the same error!any solution to it?
