### ISSUE TITLE
IndexError: string index out of range

### ISSUE THREAD

**Issue by olitoni** [mxrch/GHunt#125]
Hey, with some emails im getting this error:

```
Activated Google services :
- Youtube
- Photos
- Maps
Traceback (most recent call last):
  File "hunt.py", line 123, in <module>
    data = ytb.get_channels(client, name, config.data_path,
  File "E:\Useful\GHunt\lib\youtube.py", line 87, in get_channels
    from_gdocs = youtube_channel_search_gdocs(client, query, data_path, gdocs_public_doc)
  File "E:\Useful\GHunt\lib\youtube.py", line 44, in youtube_channel_search_gdocs
    search_results = gdoc_search(search_query, data_path, gdocs_public_doc)
  File "E:\Useful\GHunt\lib\search.py", line 24, in search
    title = result[0][1]
IndexError: string index out of range
```

**Comment by mxrch** [comment]
Hello @olitoni , I'll take a look at it, can you send me the email in dm ? Not needed but it would help my debug and fix

**Comment by olitoni** [comment]
Added you on discord / Olitoni#5539
