### ISSUE TITLE
httpx.ConnectError: [Errno 0] Error

### ISSUE THREAD

**Issue by Jackyhhh** [mxrch/GHunt#140]
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\httpx\_exceptions.py", line 326, in map_exceptions
    yield
  File "C:\ProgramData\Anaconda3\lib\site-packages\httpx\_client.py", line 866, in _send_single_request
    ext={"timeout": timeout.as_dict()},
  File "C:\ProgramData\Anaconda3\lib\site-packages\httpcore\_sync\http_proxy.py", line 125, in request
    method, url, headers=headers, stream=stream, ext=ext
  File "C:\ProgramData\Anaconda3\lib\site-packages\httpcore\_sync\http_proxy.py", line 211, in _tunnel_request
    b"CONNECT", connect_url, headers=connect_headers, ext=ext
  File "C:\ProgramData\Anaconda3\lib\site-packages\httpcore\_sync\connection.py", line 87, in request
    self.socket = self._open_socket(timeout)
  File "C:\ProgramData\Anaconda3\lib\site-packages\httpcore\_sync\connection.py", line 113, in _open_socket
    local_address=self.local_address,
  File "C:\ProgramData\Anaconda3\lib\site-packages\httpcore\_backends\sync.py", line 144, in open_tcp_stream
    return SyncSocketStream(sock=sock)
  File "C:\ProgramData\Anaconda3\lib\contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\ProgramData\Anaconda3\lib\site-packages\httpcore\_exceptions.py", line 12, in map_exceptions
    raise to_exc(exc) from None
httpcore.ConnectError: [Errno 0] Error

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "check_and_gen.py", line 136, in <module>
    html = get_authorization_source(cookies)
  File "check_and_gen.py", line 38, in get_authorization_source
    cookies=cookies, headers=config.headers, allow_redirects=False)
  File "C:\ProgramData\Anaconda3\lib\site-packages\httpx\_api.py", line 193, in get
    trust_env=trust_env,
  File "C:\ProgramData\Anaconda3\lib\site-packages\httpx\_api.py", line 104, in request
    allow_redirects=allow_redirects,
  File "C:\ProgramData\Anaconda3\lib\site-packages\httpx\_client.py", line 734, in request
    request, auth=auth, allow_redirects=allow_redirects, timeout=timeout
  File "C:\ProgramData\Anaconda3\lib\site-packages\httpx\_client.py", line 772, in send
    history=[],
  File "C:\ProgramData\Anaconda3\lib\site-packages\httpx\_client.py", line 809, in _send_handling_auth
    history=history,
  File "C:\ProgramData\Anaconda3\lib\site-packages\httpx\_client.py", line 837, in _send_handling_redirects
    response = self._send_single_request(request, timeout)
  File "C:\ProgramData\Anaconda3\lib\site-packages\httpx\_client.py", line 866, in _send_single_request
    ext={"timeout": timeout.as_dict()},
  File "C:\ProgramData\Anaconda3\lib\contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\ProgramData\Anaconda3\lib\site-packages\httpx\_exceptions.py", line 343, in map_exceptions
    raise mapped_exc(message, **kwargs) from exc  # type: ignore
httpx.ConnectError: [Errno 0] Error

**Comment by mxrch** [comment]
@Jackyhhh is this happening everytime ?

**Comment by mxrch** [comment]
Which Python version do you use ? On what operating system are you ?

**Comment by lusifer123** [comment]
I am facing Same issue... I am using Kali 2020 os. And python 3.8.4 version.. whenever i type the values of
3PSID ==>
APISID ==>
SAPISID ==>
HSID ==>

It's shows error..

**Comment by lusifer123** [comment]
> Which Python version do you use ? On what operating system are you ?



> @Jackyhhh is this happening everytime ?

Yes everytime
