### ISSUE TITLE
Chrome Start Error

### ISSUE THREAD

**Issue by yazarneon** [mxrch/GHunt#16]
Hi,

I got this error when I fill all cookies in check_and_gen.py

How I can fix this?

[+] The cookies seems valid ! Generating the Google Docs and Hangouts token...

Google Docs Token => MyToken:1111111111111
Traceback (most recent call last):
  File "check_and_gen.py", line 74, in <module>
    driver = webdriver.Chrome(executable_path=driverpath, seleniumwire_options=options, options=chrome_options)
  File "/usr/local/lib/python3.7/site-packages/seleniumwire/webdriver/browser.py", line 86, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 81, in __init__
    desired_capabilities=desired_capabilities)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)

**Comment by PinkDev1** [comment]
Tell us version info.
Wich chrome, webdriver, python version, and OS

**Comment by mxrch** [comment]
Thank you @PinkDev1 to help me with the issues / pull requests, appreciate it !
@yazarneon  You are not the only person to have this error but it's related to Chromedriver, see this issue : https://github.com/mxrch/GHunt/issues/2
I label this issue as duplicate but not closing it now, maybe you'll find a fix through the StackOverflow topics !

**Comment by RaJ4580** [comment]
Isn't it the python version? 
support !
