### ISSUE TITLE
Error when running check_and_gen.py

### ISSUE THREAD

**Issue by tobi437a** [mxrch/GHunt#162]
When i try and run python3 check_and_gen.py i get this error.

Traceback (most recent call last):I'm downloading and installing it for you...
  File "check_and_gen.py", line 102, in <module>
    driverpath        = get_driverpath()
  File "/home/tobi437a/GHunt/lib/utils.py", line 99, in get_driverpath
    path = chromedriver_autoinstaller.install(cwd=True)
  File "/home/tobi437a/.local/lib/python3.8/site-packages/chromedriver_autoinstaller/__init__.py", line 15, in install
    chromedriver_filepath = utils.download_chromedriver(cwd)
  File "/home/tobi437a/.local/lib/python3.8/site-packages/chromedriver_autoinstaller/utils.py", line 166, in download_chromedriver
    chrome_version = get_chrome_version()
  File "/home/tobi437a/.local/lib/python3.8/site-packages/chromedriver_autoinstaller/utils.py", line 107, in get_chrome_version
    with subprocess.Popen([executable_name, '--version'], stdout=subprocess.PIPE) as proc:
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'google-chrome'

I tried to create a folder called "google-chrome" in the GHunt folder but that didn't help (Im not that good at Github stuff so i dont even know if i needed to do that). I have the chromedriver folder in the GHunt folder.

**Comment by mxrch** [comment]
Hello @tobi437a, try installing Google Chrome and retry.

**Comment by tobi437a** [comment]
I installed Google Chrome, tried again and got this

Traceback (most recent call last):
  File "/home/tobi437a/.local/lib/python3.8/site-packages/selenium/webdriver/common/service.py", line 72, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: '/home/tobi437a/GHunt/chromedriver_win32'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "check_and_gen.py", line 159, in <module>
    auth_token, hangouts_token = get_hangouts_tokens(cookies, driverpath)
  File "check_and_gen.py", line 68, in get_hangouts_tokens
    driver = webdriver.Chrome(
  File "/home/tobi437a/.local/lib/python3.8/site-packages/seleniumwire/webdriver/browser.py", line 96, in __init__
    super().__init__(*args, **kwargs)
  File "/home/tobi437a/.local/lib/python3.8/site-packages/selenium/webdriver/chrome/webdriver.py", line 92, in __init__
    self.service.start()
  File "/home/tobi437a/.local/lib/python3.8/site-packages/selenium/webdriver/common/service.py", line 86, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'chromedriver_win32' executable may have wrong permissions. Please see https://sites.google.com/a/chromium.org/chromedriver/home

I thought i could fix this by typing sudo in front but then i got this

Traceback (most recent call last):
  File "check_and_gen.py", line 8, in <module>
    import httpx
ModuleNotFoundError: No module named 'httpx'

**Comment by mxrch** [comment]
@tobi437a be sure to do what's in the readme, you didn't installed the requirements.
