### ISSUE TITLE
Issue when running hunt.py

### ISSUE THREAD

**Issue by Navaxrro** [mxrch/GHunt#167]
Get this error when running 
`python hunt.py email@gmail.com
`

Running **python 3.7.9**

```
Traceback (most recent call last):
  File "hunt.py", line 54, in <module>
    name = get_account_name(client, gaiaID)
  File "C:\git\GHunt\lib\utils.py", line 37, in get_account_name
    name = gmaps_source.split("Contributions by")[1].split('"')[0].strip()
IndexError: list index out of range
```

would appreciate if any of you guys could tell me If I am doing something wrong

you have a great day

**Comment by Navaxrro** [comment]
just checked cookies with 
`check_and_gen.py`

and everything seems fine, just to check that out

**Comment by Navaxrro** [comment]
solved it, Cookie related
