### ISSUE TITLE
i am getting this issue, even when i am on my google account instection cookies page.

### ISSUE THREAD

**Issue by afiqnazeer** [mxrch/GHunt#178]
*Trace Back*

- [ ] 
![Screenshot (1)](https://user-images.githubusercontent.com/62737721/103356687-75389a80-4ad7-11eb-86b1-69901998d408.png)
 _**__Traceback (most recent call last):I'm downloading and installing it for you...

  File "/home/afiqahmad/GHunt/check_and_gen.py", line 102, in <module>
    driverpath        = get_driverpath()
  File "/home/afiqahmad/GHunt/lib/utils.py", line 101, in get_driverpath
    path = chromedriver_autoinstaller.install(cwd=True)
  File "/usr/local/lib/python3.9/dist-packages/chromedriver_autoinstaller/__init__.py", line 15, in install
    chromedriver_filepath = utils.download_chromedriver(cwd)
  File "/usr/local/lib/python3.9/dist-packages/chromedriver_autoinstaller/utils.py", line 166, in download_chromedriver
    chrome_version = get_chrome_version()
  File "/usr/local/lib/python3.9/dist-packages/chromedriver_autoinstaller/utils.py", line 107, in get_chrome_version
    with subprocess.Popen([executable_name, '--version'], stdout=subprocess.PIPE) as proc:
  File "/usr/lib/python3.9/subprocess.py", line 947, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1819, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)_
FileNotFoundError: [Errno 2] No such file or directory: 'google-chrome'_**_

**Comment by OutisNoMore** [comment]
Although I am not sure exactly what is causing the error, it can be fixed if you manually install the chromedriver from here: "https://chromedriver.chromium.org/". The chromedriver needs to be installed/extracted into the GHunt folder to work properly.
