### ISSUE TITLE
check_and_gen: list index out of range

### ISSUE THREAD

**Issue by thnglee** [mxrch/GHunt#180]
Traceback (most recent call last):I'm downloading and installing it for you...
  File "C:\Users\HP\GHunt\check_and_gen.py", line 102, in <module>
    driverpath        = get_driverpath()
  File "C:\Users\HP\GHunt\lib\utils.py", line 101, in get_driverpath
    path = chromedriver_autoinstaller.install(cwd=True)
  File "C:\Users\HP\AppData\Roaming\Python\Python39\site-packages\chromedriver_autoinstaller\__init__.py", line 15, in install
    chromedriver_filepath = utils.download_chromedriver(cwd)
  File "C:\Users\HP\AppData\Roaming\Python\Python39\site-packages\chromedriver_autoinstaller\utils.py", line 166, in download_chromedriver
    chrome_version = get_chrome_version()
  File "C:\Users\HP\AppData\Roaming\Python\Python39\site-packages\chromedriver_autoinstaller\utils.py", line 117, in get_chrome_version
    version = process.communicate()[0].decode('UTF-8').strip().split()[-1]
IndexError: list index out of range

**Comment by AngelGatewood** [comment]
Thanks for closing the issue without giving anyone an explanation of your solution, really helpful of you.
