### ISSUE TITLE
Cannot run check_and_gen.py

### ISSUE THREAD

**Issue by darthsnarkey** [mxrch/GHunt#181]
when I run $python check_and_gen.py it asks for all the cookies and is happy with them, it generates the google docs token but then crashes on the hangouts token:

Traceback (most recent call last):
  File "check_and_gen.py", line 159, in <module>
    auth_token, hangouts_token = get_hangouts_tokens(cookies, driverpath)
  File "check_and_gen.py", line 80, in get_hangouts_tokens
    driver.get("https://hangouts.google.com")
  File "/home/darthsnarkey/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/darthsnarkey/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/darthsnarkey/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=87.0.4280.88)

**Comment by saduqur80** [comment]
Git diff

**Comment by saduqur80** [comment]
Thank

**Comment by 00-cardzz** [comment]
Did you ever solve this issue, I got the same problem.

**Comment by Masiyahya** [comment]
same issue here

**Comment by darthsnarkey** [comment]
I simply had to manually choose what to scan for and omit the hangouts

**Comment by Masiyahya** [comment]
is their a command to do this?

**Comment by Masiyahya** [comment]
page crash after cookies are valid?
