### ISSUE TITLE
socket.gaierror: [Errno 11004] getaddrinfo failed at making requestpeople/me/blockedPeople request

### ISSUE THREAD

**Issue by n0101** [mxrch/GHunt#182]
Running on Windows, Python 3.8.6.

```
Do you want to enter new browser cookies from accounts.google.com ? (Y/n) Y
SID => xxxxx
SSID => xxxxx
APISID =>xxxxx
SAPISID => xxxxx
HSID => xxxxx

[+] The cookies seems valid !
Generating the Google Docs and Hangouts token...

Google Docs Token => xxxxx
Error making requestpeople/me/blockedPeople request, it can takes a few minutes...
Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\seleniumwire\proxy\proxy2.py", line 91, in proxy_request
    conn.request(self.command, path, req_body, dict(req.headers))
  File "C:\Python38\lib\http\client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Python38\lib\http\client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Python38\lib\http\client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Python38\lib\http\client.py", line 1010, in _send_output
    self.send(msg)
  File "C:\Python38\lib\http\client.py", line 950, in send
    self.connect()
  File "C:\Python38\lib\site-packages\seleniumwire\proxy\proxy2.py", line 368, in connect
    super().connect()
  File "C:\Python38\lib\http\client.py", line 1417, in connect
    super().connect()
  File "C:\Python38\lib\http\client.py", line 921, in connect
    self.sock = self._create_connection(
  File "C:\Python38\lib\socket.py", line 787, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "C:\Python38\lib\socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11004] getaddrinfo failed
Authorization Token => SAPISIDHASH xxxxx
Hangouts Token =>xxxxx
```

I'm able to run python hunt.py some@gmail.com and it generates output but some of the data returned is incorrect.  I tested on an account with Google Maps Reviews and a Public Calendar with events but it returns "No reviews" and "No Google Public Calendar found".  Checked my data.txt and all fields have values.

```
  "auth": "xxxxxxx",
    "keys": {
        "gdoc": "xxxxxxx",
        "hangouts": "xxxxxxx"`
    },
    "cookies": {
        "SID": "xxxxxxx",
        "SSID": "xxxxxxx",
        "APISID": "xxxxxxx",
        "SAPISID": "xxxxxxx",
        "HSID": "xxxxxxx",
        "CONSENT": "YES+FR.fr+V10+BX"
    }
}
```

**Comment by n0101** [comment]
is this somehow related to issue #56 ?

**Comment by mxrch** [comment]
> 
> 
> is this somehow related to issue #56 ?

Nope, it was a problem with the Selenium waiting, here I don't know, you maybe have a proxy / VPN or something broken ☹️
