### ISSUE TITLE
string index out of range

### ISSUE THREAD

**Issue by byhardest** [mxrch/GHunt#183]
any idea of what could be?

After displaying activated google services, last one was - Maps

Traceback (most recent call last):
  File "hunt.py", line 132, in <module>
    config.gdocs_public_doc)
  File "/home/hardest/OSINT/ghunt/lib/youtube.py", line 87, in get_channels
    from_gdocs = youtube_channel_search_gdocs(client, query, data_path, gdocs_public_doc)
  File "/home/hardest/OSINT/ghunt/lib/youtube.py", line 44, in youtube_channel_search_gdocs
    search_results = gdoc_search(search_query, data_path, gdocs_public_doc)
  File "/home/hardest/OSINT/ghunt/lib/search.py", line 24, in search
    title = result[0][1]
IndexError: string index out of range

**Comment by mxrch** [comment]
Hi @byhardest, does the https://github.com/mxrch/GHunt/commit/131ea721b94f7173309881efbf3e3013832cb53b commit fixes your issue ?
