### ISSUE TITLE
check_and_gen.py unable to install chromedriver

### ISSUE THREAD

**Issue by KB-Q** [mxrch/GHunt#195]
When I run: `python3 check_and_gen.py`, I get this error:

        `Traceback (most recent call last):I'm downloading and installing it for you...  
        File "check_and_gen.py", line 102, in <module>
        driverpath        = get_driverpath() 
        File "/home/karthik_balaji/GHunt/lib/utils.py", line 101, in get_driverpath
        path = chromedriver_autoinstaller.install(cwd=True)
        File "/home/karthik_balaji/.local/lib/python3.8/site-packages/chromedriver_autoinstaller/__init__.py", line 15, in install
        chromedriver_filepath = utils.download_chromedriver(cwd)
        File "/home/karthik_balaji/.local/lib/python3.8/site-packages/chromedriver_autoinstaller/utils.py", line 166, in download_chromedriver
        chrome_version = get_chrome_version()
        File "/home/karthik_balaji/.local/lib/python3.8/site-packages/chromedriver_autoinstaller/utils.py", line 107, in get_chrome_version
        with subprocess.Popen([executable_name, '--version'], stdout=subprocess.PIPE) as proc:
        File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
        self._execute_child(args, executable, preexec_fn, close_fds,
        File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
        FileNotFoundError: [Errno 2] No such file or directory: 'google-chrome'`

The check_and_gen.py script doesn't install the chromedriver automatically, as described in the README. If it's a bug, kindly fix it, if not, let me know a workaround. Thank you.

**Comment by snoozedesert** [comment]
same pls help me, i'm using firefox

**Comment by aditya-wate** [comment]
You'd need to install chrome or chromium.

This should do the trick:

```bash
 sudo apt install chromium-browser
```

**Comment by KOBAJIT** [comment]
> You'd need to install chrome or chromium.
> 
> This should do the trick for chromium:
> 
> ```shell
>  sudo apt install chromium-browser
> ```
> 
> Easier would be to install chrome though.

 installed Chrome, still the same problem

**Comment by megustalafantabienfria** [comment]
Same issue here! Already have google chrome installed...

**Comment by 05x90fm** [comment]
1. Chromedriver & Google Chrome
This project uses Selenium, so you'll need to download the chromedriver here : https://chromedriver.chromium.org/downloads
And put it in the GHunt folder. Be sure it's called "chromedriver.exe" or "chromedriver".
Also, be sure to have Google Chrome installed.

2. In the GHunt folder, do this:

`python3 -m pip install -r requirements.txt`

3. Usage
`python3 check_and_gen.py`


It worked for me
