### ISSUE TITLE
Error check_and_gen.py

### ISSUE THREAD

**Issue by nguyen151095** [mxrch/GHunt#199]
Error making requestmepage...
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/seleniumwire/proxy/proxy2.py", line 92, in proxy_request
    res = conn.getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1347, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

**Comment by mxrch** [comment]
Either you have a bad connection, either you should retry.
Connection problems sometimes occur.
