### ISSUE TITLE
Docker Trace back error

### ISSUE THREAD

**Issue by tej0402** [mxrch/GHunt#207]
Hi,

While I am running with docker image I am getting the below error message. I have checked my tokens those are valid. Help is appreciated.

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/httpx/_exceptions.py", line 326, in map_exceptions
    yield
  File "/usr/local/lib/python3.8/site-packages/httpx/_client.py", line 861, in _send_single_request
    (status_code, headers, stream, ext) = transport.request(
  File "/usr/local/lib/python3.8/site-packages/httpcore/_sync/connection_pool.py", line 218, in request
    response = connection.request(
  File "/usr/local/lib/python3.8/site-packages/httpcore/_sync/connection.py", line 106, in request
    return self.connection.request(method, url, headers, stream, ext)
  File "/usr/local/lib/python3.8/site-packages/httpcore/_sync/http11.py", line 72, in request
    ) = self._receive_response(timeout)
  File "/usr/local/lib/python3.8/site-packages/httpcore/_sync/http11.py", line 133, in _receive_response
    event = self._receive_event(timeout)
  File "/usr/local/lib/python3.8/site-packages/httpcore/_sync/http11.py", line 172, in _receive_event
    data = self.socket.read(self.READ_NUM_BYTES, timeout)
  File "/usr/local/lib/python3.8/site-packages/httpcore/_backends/sync.py", line 62, in read
    return self.sock.recv(n)
  File "/usr/local/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.8/site-packages/httpcore/_exceptions.py", line 12, in map_exceptions
    raise to_exc(exc) from None
httpcore.ReadTimeout: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "hunt.py", line 131, in <module>
    data = ytb.get_channels(client, name, config.data_path,
  File "/usr/src/app/lib/youtube.py", line 86, in get_channels
    from_gdocs = youtube_channel_search_gdocs(client, query, data_path, gdocs_public_doc)
  File "/usr/src/app/lib/youtube.py", line 76, in youtube_channel_search_gdocs
    req = client.get(avatar_link)
  File "/usr/local/lib/python3.8/site-packages/httpx/_client.py", line 907, in get
    return self.request(
  File "/usr/local/lib/python3.8/site-packages/httpx/_client.py", line 733, in request
    return self.send(
  File "/usr/local/lib/python3.8/site-packages/httpx/_client.py", line 767, in send
    response = self._send_handling_auth(
  File "/usr/local/lib/python3.8/site-packages/httpx/_client.py", line 805, in _send_handling_auth
    response = self._send_handling_redirects(
  File "/usr/local/lib/python3.8/site-packages/httpx/_client.py", line 837, in _send_handling_redirects
    response = self._send_single_request(request, timeout)
  File "/usr/local/lib/python3.8/site-packages/httpx/_client.py", line 861, in _send_single_request
    (status_code, headers, stream, ext) = transport.request(
  File "/usr/local/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.8/site-packages/httpx/_exceptions.py", line 343, in map_exceptions
    raise mapped_exc(message, **kwargs) from exc  # type: ignore
httpx.ReadTimeout: The read operation timed out

**Comment by mxrch** [comment]
You maybe have a bad connection or you are behind a proxy / vpn.

**Comment by tej0402** [comment]
No I am not using VPN/Proxy, my connection is good though....But I am running Docker image inside my Virutalbox Kali machine.
