### ISSUE TITLE
Cookies valid but there is an error

### ISSUE THREAD

**Issue by ntai1** [mxrch/GHunt#226]
[+] The cookies seems valid !
Traceback (most recent call last):
  File "/home/tometjazz/GHunt/check_and_gen.py", line 196, in <module>
    driver = webdriver.Chrome(
  File "/home/tometjazz/.local/lib/python3.9/site-packages/seleniumwire/webdriver/browser.py", line 96, in __init__
    super().__init__(*args, **kwargs)
  File "/home/tometjazz/.local/lib/python3.9/site-packages/selenium/webdriver/chrome/webdriver.py", line 76, in __init__
    RemoteWebDriver.__init__(
  File "/home/tometjazz/.local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/tometjazz/.local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/tometjazz/.local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/tometjazz/.local/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 90
Current browser version is 89.0.4389.82 with binary path /usr/bin/chromium

**Comment by DelegateZero** [comment]
Download the latest GHunt-master folder and try again.

**Comment by StigP1337** [comment]
The ChromeDriver version needs to match exactly your Chrome browser version. As stated at the end of the error message you have ChromeDriver version 90 installed, but your Chrome browser version is 89.0.4389.82. You have to install ChromeDriver version 89 first.
