### ISSUE TITLE
It doesn't give me the tokens  

### ISSUE THREAD

**Issue by LeHak0** [mxrch/GHunt#231]
python3 check_and_gen.py                                                                  127 ⨯
[-] No stored cookies found

Enter these browser cookies found at accounts.google.com :
SID => 
SSID => 
APISID => 
SAPISID =>
HSID => 
[+] The cookies seems valid !
Traceback (most recent call last):
  File "/home/kali/GHunt/check_and_gen.py", line 196, in <module>
    driver = webdriver.Chrome(
  File "/usr/local/lib/python3.9/dist-packages/seleniumwire/webdriver.py", line 109, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/chrome/webdriver.py", line 95, in __init__
    RemoteWebDriver.__init__(
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 152, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 249, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 318, in execute
    self.error_handler.check_response(response)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 86
Current browser version is 89.0.4389.114 with binary path /usr/bin/google-chrome

-------------------------------------------------------------------------------------
When I paste the cookies it says than they are valid but after it does not run the program for the tokens

**Comment by StigP1337** [comment]
The ChromeDriver version needs to match exactly your Chrome browser version. As stated at the end of the error message you have ChromeDriver version 86 installed, but your Chrome browser version is 89.0.4389.114. You have to install ChromeDriver version 89.0.4389.114 first.

**And NEVER post your session cookie values in public!**

**Comment by LeHak0** [comment]
okay thank you 
sorry for that
