### ISSUE TITLE
issues in python3 check_and_gen.py

### ISSUE THREAD

**Issue by msmharbi** [mxrch/GHunt#236]
its keep give this massage... my googlechrome v is :  Version 89.0.4389.114 (Official Build) (64-bit)
and ChromeDriver 89.0.4389.90 
 

Google Docs Token => AC4w5VgND4OtXRiEnYxPi-UGRF8oEanu5Q:1618749789070
Traceback (most recent call last):
  File "/home/msmharbi/GHunt/check_and_gen.py", line 212, in <module>
    internal_auth, internal_token = get_internal_tokens(driver, cookies, tmprinter)
  File "/home/msmharbi/GHunt/check_and_gen.py", line 117, in get_internal_tokens
    driver.get("https://drive.google.com/drive/my-drive")
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 330, in get
    self.execute(Command.GET, {'url': url})
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 318, in execute
    self.error_handler.check_response(response)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 299.247
  (Session info: headless chrome=89.0.4389.114)

**Comment by longldktmm** [comment]
I error too
Traceback (most recent call last):
  File "E:\git\GHunt-master\check_and_gen.py", line 212, in <module>
    internal_auth, internal_token = get_internal_tokens(driver, cookies, tmprinter)
  File "E:\git\GHunt-master\check_and_gen.py", line 120, in get_internal_tokens
    internal_token = body.split("appsitemsuggest-pa")[1].split(",")[3].strip('"')
IndexError: list index out of range
