### ISSUE TITLE
This version of ChromeDriver only supports Chrome version 83

### ISSUE THREAD

**Issue by kukurikapu0102** [mxrch/GHunt#238]
[+] The cookies seems valid !
Traceback (most recent call last):
  File "/root/GHunt/check_and_gen.py", line 196, in <module>
    driver = webdriver.Chrome(
  File "/usr/local/lib/python3.9/dist-packages/seleniumwire/webdriver.py", line 114, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/chrome/webdriver.py", line 95, in __init__
    RemoteWebDriver.__init__(
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 152, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 249, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 318, in execute
    self.error_handler.check_response(response)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 83

**Comment by deltabravozulu** [comment]
You probably have a separate installation installed.

**Comment by deltabravozulu** [comment]
Type "which chromedriver" into terminal and see what your computer is using. @mxrch  you should probably just have your script download the chromedriver into docker/the cloned repo and use it regardless of whether it is installed or not. It's a pretty tiny file, after all, and people who have another chromedriver somewhere in their PATH will be sort of screwed because the detection mechanism doesn't look to see if the chromedriver version matches with the currently installed primary version of Chrome.

**Comment by kukurikapu0102** [comment]
Will try bro, Thanks alot!

**Comment by deltabravozulu** [comment]
Sure thing!

**Comment by Sachin6752** [comment]
Nice
