### ISSUE TITLE
New error after recent update (today)

### ISSUE THREAD

**Issue by tsmitsmitonline** [mxrch/GHunt#251]
Traceback (most recent call last):
  File "ghunt.py", line 11, in <module>
    from modules.youtube import youtube_hunt
  File "/usr/src/app/modules/youtube.py", line 15, in <module>
    from bs4 import BeautifulSoup as bs
ModuleNotFoundError: No module named 'bs4'

**Comment by mxrch** [comment]
fixed !

**Comment by tsmitsmitonline** [comment]
It works again, thanks for fixing
