### ISSUE TITLE
failed parse reviews

### ISSUE THREAD

**Issue by johnny-silverhand** [mxrch/GHunt#259]
```python
[+] 1 reviews found !
Traceback (most recent call last):
  File "ghunt.py", line 35, in <module>
    email_hunt(data)
  File "/usr/src/app/modules/email.py", line 161, in email_hunt
    reviews = gmaps.scrape(gaiaID, client, cookies, config, config.headers, config.regexs["review_loc_by_id"], config.headless)
  File "/usr/src/app/lib/gmaps.py", line 122, in scrape
    date = get_datetime(stars.find_element_by_xpath("following-sibling::span").text)
  File "/usr/src/app/lib/gmaps.py", line 22, in get_datetime
    nb = int(datepublished.split()[0])
ValueError: invalid literal for int() with base 10: 'just'
```

**Comment by hukum23** [comment]
![IMG_20210809_205428.jpg](https://user-images.githubusercontent.com/82059027/128734176-f305c94e-750c-4dfd-a3f9-9b14bda18f64.jpg)
