### ISSUE TITLE
Traceback when searching docs

### ISSUE THREAD

**Issue by gcleaves** [mxrch/GHunt#264]
Hello, I have searched for 2 docs (different owners) and each time I got a traceback error. Email searches work without error.

```
$ docker run -v ghunt-resources:/usr/src/app/resources -ti mxrch/ghunt ghunt.py doc https://docs.google.com/document/d/1qQ6JWBLufVqOxmkyemC9etsQYhGDEGVlOyyygB9XdXs

     .d8888b.  888    888                   888
    d88P  Y88b 888    888                   888
    888    888 888    888                   888
    888        8888888888 888  888 88888b.  888888
    888  88888 888    888 888  888 888 "88b 888
    888    888 888    888 888  888 888  888 888
    Y88b  d88P 888    888 Y88b 888 888  888 Y88b.
     "Y8888P88 888    888  "Y88888 888  888  "Y888

[+] Docker detected, profile pictures will not be saved.

Document ID : 1qQ6JWBLufVqOxmkyemC9etsQYhGDEGVlOyyygB9XdXs

[+] Creation date : 2021/07/22 17:17:31 (UTC)
[+] Last edit date : 2021/07/22 17:18:49 (UTC)

Public permissions :
- reader

[+] Owner found !

Name : Vecino Navero
Email : naverovecino0603@gmail.com
Google ID : 10855971813717849528
Traceback (most recent call last):
  File "ghunt.py", line 37, in <module>
    doc_hunt(data)
  File "/usr/src/app/modules/doc.py", line 119, in doc_hunt
    profile_pic_link = owner['photoLink']
KeyError: 'photoLink'
```

**Comment by That1GuyOnTheCouch** [comment]
File changed

**Comment by gcleaves** [comment]
> File changed

What does this mean? I need to update the docker container?
