### ISSUE TITLE
[Solved] Cant not finish "ghunt check_and_gen.py"

### ISSUE THREAD

**Issue by roswitina** [mxrch/GHunt#268]
docker run -v ghunt-resources:/usr/src/app/resources -ti mxrch/ghunt check_and_gen.py
```
[-] No stored cookies found

Enter these browser cookies found at accounts.google.com :
SID => Cookie.............................
SSID => Cookie......................
APISID => Cookie........................
SAPISID => Cookie......................
HSID => Cookie.....................

[+] The cookies seems valid !
Extracting the tokens...

Google Docs Token => Token..............................
Internal APIs Token => Token...................
Internal APIs Authorization => SAPISIDHASH Authorisation..............................
Traceback (most recent call last):
  File "check_and_gen.py", line 217, in <module>
    auth_token, hangouts_token = get_hangouts_tokens(driver, cookies, tmprinter)
  File "check_and_gen.py", line 76, in get_hangouts_tokens
    driver.close()
  File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 688, in close
    self.execute(Command.CLOSE)
  File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: headless chrome=91.0.4472.164)

```
root@debian11:/opt#

**Comment by roswitina** [comment]
This trial took place in a Linux VM; without a desktop interface.

I have now carried out the installation under Windows and everything works. 

Thank you.

**Comment by roswitina** [comment]
The error was before the computer.....
Ashes on my head....
