### ISSUE TITLE
Check and Gen.py Error

### ISSUE THREAD

**Issue by RocketNinja15** [mxrch/GHunt#273]
[+] The cookies seems valid !
Traceback (most recent call last):
  File "C:\Users\Rocket\GHunt\check_and_gen.py", line 196, in <module>
    driver = webdriver.Chrome(
  File "C:\Users\Rocket\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\seleniumwire\webdriver.py", line 168, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\Rocket\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\selenium\webdriver\chrome\webdriver.py", line 76, in __init__
    RemoteWebDriver.__init__(
  File "C:\Users\Rocket\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\Rocket\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\Rocket\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Rocket\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 91
Current browser version is 93.0.4577.63 with binary path C:\Program Files\Google\Chrome\Application\chrome.exe

**Comment by mxrch** [comment]
Delete the folder "91" in GHunt folder

**Comment by zakzico** [comment]
There isn't any "91" folder. I got the same error, I can't seem to run Ghunt, every time I run it. I t tells me " Please generate cookies and tokens first, with the check_and_gen.py script " and when I run check_and_gen.py the above error pops up. 

Did any =one encounter the same problem and found a solution. Please let us know

**Comment by beni2a** [comment]
Hi all, +1 for the same error...
Used Brave, Firefox, Chrome, manual and Ghunt companion, deleted docker and used 2 method from companion.... still doesn't work... Any idea?
