### ISSUE TITLE
How to fix this ? This version of ChromeDriver only supports Chrome version 79

### ISSUE THREAD

**Issue by haszimoto** [mxrch/GHunt#279]
[+] The cookies seems valid !
Traceback (most recent call last):
  File "/root/GHunt/check_and_gen.py", line 196, in <module>
    driver = webdriver.Chrome(
  File "/usr/local/lib/python3.9/dist-packages/seleniumwire/webdriver.py", line 168, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/chrome/webdriver.py", line 95, in __init__
    RemoteWebDriver.__init__(
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 152, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 249, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 318, in execute
    self.error_handler.check_response(response)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 79

**Comment by meticulousCraftman** [comment]
I have the same problem. 
Here is the result after running  **check_and_gen.py**.

```

[+] The cookies seems valid !
Traceback (most recent call last):
  File "check_and_gen.py", line 196, in <module>
    driver = webdriver.Chrome(
  File "/usr/local/lib/python3.8/site-packages/seleniumwire/webdriver.py", line 120, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/chrome/webdriver.py", line 76, in __init__
    RemoteWebDriver.__init__(
  File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: crashed.
  (chrome not reachable)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
```

**Comment by dhiazulfa** [comment]
Update your chromedriver. Download chrome driver manualy here:  https://chromedriver.storage.googleapis.com/index.html

**Comment by C3n7ral051nt4g3ncy** [comment]
It means that you have a different unsupported version. This seems to be what you are looking for: [V79](https://chromedriver.storage.googleapis.com/index.html?path=79.0.3945.16/)

> [+] The cookies seems valid !
> Traceback (most recent call last):
> File "/root/GHunt/check_and_gen.py", line 196, in 
> driver = webdriver.Chrome(
> File "/usr/local/lib/python3.9/dist-packages/seleniumwire/webdriver.py", line 168, in **init**
> super().**init**(*args, **kwargs)
> File "/usr/lib/python3/dist-packages/selenium/webdriver/chrome/webdriver.py", line 95, in **init**
> RemoteWebDriver.**init**(
> File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 152, in **init**
> self.start_session(capabilities, browser_profile)
> File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 249, in start_session
> response = self.execute(Command.NEW_SESSION, parameters)
> File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 318, in execute
> self.error_handler.check_response(response)
> File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
> raise exception_class(message, screen, stacktrace)
> selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 79
