### ISSUE TITLE
Stuck on "Fetching Drive homepage..."

### ISSUE THREAD

**Issue by Arinerron** [mxrch/GHunt#288]
Tried from two separate google accounts + computers

**Comment by TrulyPain** [comment]
I have the same issue.

**Comment by eschultze** [comment]
+1 same here

**Comment by mxrch** [comment]
@eschultze  Is it always the case after a git pull ?

**Comment by eschultze** [comment]
@mxrch yep, I had just done a git pull, just in case, because I had not used ghunt in a couple of months. Also, my chromedrive was at version 91, so I had to erase it and allow pip to install the newest one.

**Comment by eschultze** [comment]
New attempt with fresh install here. The last text was "Fetching Drive homepage" but after hitting ctrl+c it changed to "Generating OSID for the Cloud Console".

```
Choice => 1
GHunt is listening on port 60067...
[+] Received cookies !

[+] The cookies seems valid !
Extracting the tokens...

Google Docs Token => redacted
Generating OSID for the Cloud Console...
^CTraceback (most recent call last):
  File "/Users/redacted/scripts/ghunt/check_and_gen.py", line 294, in <module>
    internal_auth, internal_token = get_internal_tokens(driver, cookies_with_osid, tmprinter)
  File "/Users/redacted/scripts/ghunt/check_and_gen.py", line 126, in get_internal_tokens
    driver.get("https://drive.google.com/drive/my-drive")
  File "/Users/redacted/.virtualenvs/ghunt/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 436, in get
    self.execute(Command.GET, {'url': url})
  File "/Users/redacted/.virtualenvs/ghunt/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 422, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/Users/redacted/.virtualenvs/ghunt/lib/python3.9/site-packages/selenium/webdriver/remote/remote_connection.py", line 421, in execute
    return self._request(command_info[0], url, body=data)
  File "/Users/redacted/.virtualenvs/ghunt/lib/python3.9/site-packages/selenium/webdriver/remote/remote_connection.py", line 443, in _request
    resp = self._conn.request(method, url, body=body, headers=headers)
  File "/Users/redacted/.virtualenvs/ghunt/lib/python3.9/site-packages/urllib3/request.py", line 78, in request
    return self.request_encode_body(
  File "/Users/redacted/.virtualenvs/ghunt/lib/python3.9/site-packages/urllib3/request.py", line 170, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/Users/redacted/.virtualenvs/ghunt/lib/python3.9/site-packages/urllib3/poolmanager.py", line 375, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/Users/redacted/.virtualenvs/ghunt/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/Users/redacted/.virtualenvs/ghunt/lib/python3.9/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/Users/redacted/.virtualenvs/ghunt/lib/python3.9/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/Users/redacted/.pyenv/versions/3.9.0/lib/python3.9/http/client.py", line 1347, in getresponse
    response.begin()
  File "/Users/redacted/.pyenv/versions/3.9.0/lib/python3.9/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/Users/redacted/.pyenv/versions/3.9.0/lib/python3.9/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/Users/redacted/.pyenv/versions/3.9.0/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
KeyboardInterrupt
```

**Comment by aruso** [comment]
I'm getting the same issue with and without docker .... anybody have a fix?

**Comment by sypher01** [comment]
Hey guys, this is probably due to the headless chrome waiting for the page (drive.google.com) to load. 

I think its connected to some DNS blockers. 

That being said, to fix it, comment line 258 of check_and_gen.py - this will make the headless chrome open. 

When you're in the page of drive.google.com, and you see it loading indefinitely, just press "esc" to interrupt loading (on the headless chrome, not on the script!) - this will make chrome exit the waiting loop and the script will go forward.

If you don't have a GUI, you're on your own, in all probability you need to set a timeout (line 252) of about 10-15 seconds. that way, it will timeout and proceed.
