### ISSUE TITLE
Error while adding cookies 

### ISSUE THREAD

**Issue by Mushebeq** [mxrch/GHunt#300]
[+] The cookies seems valid !
Traceback (most recent call last):
  File "/root/ghunt/check_and_gen.py", line 274, in <module>
    driver = webdriver.Chrome(
  File "/usr/local/lib/python3.9/dist-packages/seleniumwire/webdriver.py", line 195, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/chrome/webdriver.py", line 70, in __init__
    super(WebDriver, self).__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/chromium/webdriver.py", line 90, in __init__
    self.service.start()
  File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/common/service.py", line 98, in start
    self.assert_process_still_running()
  File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/common/service.py", line 110, in assert_process_still_running
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: Service /root/.wdm/drivers/chromedriver/linux64/96.0.4664.45/chromedriver unexpectedly exited. Status code was: 127

**Comment by Mrpolack** [comment]
same here

**Comment by ZekePolarisBSH** [comment]
Uninstall this, this tool can't be trusted the user hacks us using this tool and threatens to leak our data. I already reported this to IC3 and the FBI.

**Comment by ZekePolarisBSH** [comment]
And to this site.

**Comment by DamienBuchet** [comment]
Just install the chromium package and its dependencies
