### ISSUE TITLE
check_and_gen.py - ChromeDriver only supports Chrome version 95

### ISSUE THREAD

**Issue by jevarlet** [mxrch/GHunt#307]
I receive this error when generating cookies using check_and_gen.py:

```[+] The cookies seems valid !
Traceback (most recent call last):
  File "/Users/bindead/ghunt/check_and_gen.py", line 274, in <module>
    driver = webdriver.Chrome(
  File "/usr/local/lib/python3.9/site-packages/seleniumwire/webdriver.py", line 187, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/chrome/webdriver.py", line 69, in __init__
    super(WebDriver, self).__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/chromium/webdriver.py", line 93, in __init__
    RemoteWebDriver.__init__(
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 266, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 357, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 418, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 95
Current browser version is 97.0.4692.71 with binary path /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
Stacktrace:
0   chromedriver                        0x00000001092f8549 __gxx_personality_v0 + 573257
1   chromedriver                        0x0000000109285603 __gxx_personality_v0 + 102403
2   chromedriver                        0x0000000108e47478 chromedriver + 173176
3   chromedriver                        0x0000000108e6dcb0 chromedriver + 330928
4   chromedriver                        0x0000000108e69791 chromedriver + 313233
5   chromedriver                        0x0000000108e66299 chromedriver + 299673
6   chromedriver                        0x0000000108e9fc81 chromedriver + 535681
7   chromedriver                        0x0000000108e99a13 chromedriver + 510483
8   chromedriver                        0x0000000108e700a0 chromedriver + 340128
9   chromedriver                        0x0000000108e71305 chromedriver + 344837
10  chromedriver                        0x00000001092b589f __gxx_personality_v0 + 299679
11  chromedriver                        0x00000001092cc3da __gxx_personality_v0 + 392666
12  chromedriver                        0x00000001092d231b __gxx_personality_v0 + 417051
13  chromedriver                        0x00000001092cdafa __gxx_personality_v0 + 398586
14  chromedriver                        0x00000001092aa4ac __gxx_personality_v0 + 253612
15  chromedriver                        0x00000001092e8b78 __gxx_personality_v0 + 509304
16  chromedriver                        0x00000001092e8d01 __gxx_personality_v0 + 509697
17  chromedriver                        0x00000001092ffac8 __gxx_personality_v0 + 603336
18  libsystem_pthread.dylib             0x00007ff809e3d4f4 _pthread_start + 125
19  libsystem_pthread.dylib             0x00007ff809e3900f thread_start + 15```

**Comment by jevarlet** [comment]
Removing and reinstalling Ghunt resolved this issue.
