### ISSUE TITLE
ISSUE: function() argument 'code' must be code, not str 

### ISSUE THREAD

**Issue by Mrpolack** [mxrch/GHunt#309]
on kali 2021.1- python3 3.9.9 it gets me this error:

Traceback (most recent call last):
  File "/home/kali/ghunt/ghunt.py", line 12, in <module>
    from modules.email import email_hunt
  File "/home/kali/ghunt/modules/email.py", line 14, in <module>
    from geopy.geocoders import Nominatim
  File "/usr/local/lib/python3.9/dist-packages/geopy/__init__.py", line 12, in <module>
    from geopy.geocoders import *  # noqa
  File "/usr/local/lib/python3.9/dist-packages/geopy/geocoders/__init__.py", line 223, in <module>
    from geopy.geocoders.algolia import AlgoliaPlaces
  File "/usr/local/lib/python3.9/dist-packages/geopy/geocoders/algolia.py", line 5, in <module>
    from geopy.geocoders.base import DEFAULT_SENTINEL, Geocoder
  File "/usr/local/lib/python3.9/dist-packages/geopy/geocoders/base.py", line 7, in <module>
    from geopy.adapters import (
  File "/usr/local/lib/python3.9/dist-packages/geopy/adapters.py", line 55, in <module>
    import aiohttp
  File "/usr/lib/python3/dist-packages/aiohttp/__init__.py", line 6, in <module>
    from .client import (
  File "/usr/lib/python3/dist-packages/aiohttp/client.py", line 35, in <module>
    from . import hdrs, http, payload
  File "/usr/lib/python3/dist-packages/aiohttp/http.py", line 7, in <module>
    from .http_parser import (
  File "/usr/lib/python3/dist-packages/aiohttp/http_parser.py", line 15, in <module>
    from .helpers import NO_EXTENSIONS, BaseTimerContext
  File "/usr/lib/python3/dist-packages/aiohttp/helpers.py", line 667, in <module>
    class CeilTimeout(async_timeout.timeout):
TypeError: function() argument 'code' must be code, not str

**Comment by absecnet** [comment]
You need to update aiohttp to the latest version by using command below
`sudo pip install aiohttp==3.8.1`
