### ISSUE TITLE
unknown error: DevToolsActivePort file doesn't exist

### ISSUE THREAD

**Issue by ralghamdi** [mxrch/GHunt#317]
I was trying to run GHunt tools from Ubuntu machine and after providing the cookies it shows the below error:

[+] The cookies seems valid !
Traceback (most recent call last):
  File "check_and_gen.py", line 274, in <module>
    driver = webdriver.Chrome(
  File "/home/user/.local/lib/python3.8/site-packages/seleniumwire/webdriver.py", line 206, in __init__
    super().__init__(*args, **kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/selenium/webdriver/chrome/webdriver.py", line 70, in __init__
    super(WebDriver, self).__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "/home/user/.local/lib/python3.8/site-packages/selenium/webdriver/chromium/webdriver.py", line 93, in __init__
    RemoteWebDriver.__init__(
  File "/home/user/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 268, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/user/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 359, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/user/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 424, in execute
    self.error_handler.check_response(response)
  File "/home/user/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/chromium-browser is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
#0 0x7fe1739dd7d3 <unknown>
#1 0x7fe173739688 <unknown>
#2 0x7fe17375cb27 <unknown>
#3 0x7fe17375868f <unknown>
#4 0x7fe173793355 <unknown>
#5 0x7fe17378d5a3 <unknown>
#6 0x7fe173762ddc <unknown>
#7 0x7fe173763de5 <unknown>
#8 0x7fe173a0e49d <unknown>
#9 0x7fe173a2760c <unknown>
#10 0x7fe173a10205 <unknown>
#11 0x7fe173a27ee5 <unknown>
#12 0x7fe173a04070 <unknown>
#13 0x7fe173a43488 <unknown>
#14 0x7fe173a4360c <unknown>
#15 0x7fe173a5cc6d <unknown>
#16 0x7fe1732c6609 <unknown>

**Comment by mxrch** [comment]
Hello, you should check this with webdriver-manager developers.
