### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by fraspace5** [mxrch/GHunt#337]
Traceback (most recent call last):
  File "/home/fs45/ghunt/check_and_gen.py", line 255, in <module>
    driver = webdriver.Chrome(
  File "/home/fs45/.local/lib/python3.10/site-packages/seleniumwire/webdriver.py", line 211, in __init__
    super().__init__(*args, **kwargs)
  File "/home/fs45/.local/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 70, in __init__
    super(WebDriver, self).__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "/home/fs45/.local/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py", line 93, in __init__
    RemoteWebDriver.__init__(
  File "/home/fs45/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 269, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/fs45/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 360, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/fs45/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 425, in execute
    self.error_handler.check_response(response)
  File "/home/fs45/.local/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot find Chrome binary
Stacktrace:
#0 0x564cac905533 <unknown>
#1 0x564cac6641e8 <unknown>
#2 0x564cac685469 <unknown>
#3 0x564cac682c4a <unknown>
#4 0x564cac6bdd0a <unknown>
#5 0x564cac6b7e33 <unknown>
#6 0x564cac68d71a <unknown>
#7 0x564cac68e875 <unknown>
#8 0x564cac949e1d <unknown>
#9 0x564cac94d751 <unknown>
#10 0x564cac93407e <unknown>
#11 0x564cac94e388 <unknown>
#12 0x564cac928fe0 <unknown>
#13 0x564cac96a748 <unknown>
#14 0x564cac96a8c8 <unknown>
#15 0x564cac98470d <unknown>
#16 0x7ff549485d80 <unknown>

**Comment by mxrch** [comment]
Maybe you have Chromium and not Chrome, anyway this is an issue related to webdriver-manager.
