### ISSUE TITLE
Error Not Ruining 

### ISSUE THREAD

**Issue by muhammadubaidyousuf** [mxrch/GHunt#339]
C:\Users\Ubaid Ahmed\Downloads\GHunt-master\GHunt-master>python check_and_gen.py
Traceback (most recent call last):
  File "check_and_gen.py", line 3, in <module>
    from lib import modwall; modwall.check() # We check the requirements
  File "C:\Users\Ubaid Ahmed\Downloads\GHunt-master\GHunt-master\lib\modwall.py", line 29
    if req["specs"] and (specs := req["specs"][0]):
                               ^
SyntaxError: invalid syntax

**Comment by mxrch** [comment]
Respect the issues guideline.
