### ISSUE TITLE
check_and_gen.py

### ISSUE THREAD

**Issue by CollenMenezes** [mxrch/GHunt#344]
Traceback (most recent call last):
  File "/home/collen/ghunt/check_and_gen.py", line 201, in <module>
    driverpath = get_driverpath()
  File "/home/collen/ghunt/lib/utils.py", line 212, in get_driverpath
    chromedrivermanager_silent = ChromeDriverManager(print_first_line=False, log_level=0)
TypeError: __init__() got an unexpected keyword argument 'print_first_line'

**Comment by comste** [comment]
same issue !!!!!
