### ISSUE TITLE
Crash in check gen

### ISSUE THREAD

**Issue by TomerGamerTV** [mxrch/GHunt#347]
**Describe the bug**
```[+] The cookies seems valid !
Traceback (most recent call last):
  File "C:\Users\tomer\Downloads\ghunt\check_and_gen.py", line 255, in <module>
    driver = webdriver.Chrome(
  File "C:\Users\tomer\AppData\Roaming\Python\Python310\site-packages\seleniumwire\webdriver.py", line 211, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\tomer\AppData\Roaming\Python\Python310\site-packages\selenium\webdriver\chrome\webdriver.py", line 70, in __init__
    super(WebDriver, self).__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "C:\Users\tomer\AppData\Roaming\Python\Python310\site-packages\selenium\webdriver\chromium\webdriver.py", line 92, in __init__
    RemoteWebDriver.__init__(
  File "C:\Users\tomer\AppData\Roaming\Python\Python310\site-packages\selenium\webdriver\remote\webdriver.py", line 275, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\tomer\AppData\Roaming\Python\Python310\site-packages\selenium\webdriver\remote\webdriver.py", line 365, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\tomer\AppData\Roaming\Python\Python310\site-packages\selenium\webdriver\remote\webdriver.py", line 430, in execute
    self.error_handler.check_response(response)
  File "C:\Users\tomer\AppData\Roaming\Python\Python310\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot find Chrome binary
Stacktrace:
Backtrace:
        Ordinal0 [0x00F4D953+2414931]
        Ordinal0 [0x00EDF5E1+1963489]
        Ordinal0 [0x00DCC6B8+837304]
        Ordinal0 [0x00DE7A8E+948878]
        Ordinal0 [0x00DE5FB1+942001]
        Ordinal0 [0x00E19100+1151232]
        Ordinal0 [0x00E18D5A+1150298]
        Ordinal0 [0x00E142B6+1131190]
        Ordinal0 [0x00DEE860+976992]
        Ordinal0 [0x00DEF756+980822]
        GetHandleVerifier [0x011BCC62+2510274]
        GetHandleVerifier [0x011AF760+2455744]
        GetHandleVerifier [0x00FDEABA+551962]
        GetHandleVerifier [0x00FDD916+547446]
        Ordinal0 [0x00EE5F3B+1990459]
        Ordinal0 [0x00EEA898+2009240]
        Ordinal0 [0x00EEA985+2009477]
        Ordinal0 [0x00EF3AD1+2046673]
        BaseThreadInitThunk [0x76FDFA29+25]
        RtlGetAppContainerNamedObjectPath [0x77597A7E+286]
        RtlGetAppContainerNamedObjectPath [0x77597A4E+238]```

**To Reproduce**
Steps to reproduce the behavior:
1. idk why its happened

**Expected behavior**
to work

**System (please complete the following information):**
 - Windows 10
 - Python 3.10.4

**Comment by mxrch** [comment]
"selenium.common.exceptions.WebDriverException: Message: unknown error: cannot find Chrome binary" Install Chrome, as described in the ReadMe, and make sure it's in your path.

**Comment by mxrch** [comment]
See : https://github.com/mxrch/GHunt/issues/330

**Comment by TomerGamerTV** [comment]
> "selenium.common.exceptions.WebDriverException: Message: unknown error: cannot find Chrome binary" Install Chrome, as described in the ReadMe, and make sure it's in your path.

its showing me this error even when i downloaded everything ```I can't find the library geopy, did you correctly installed the libraries specified in requirements.txt ? ```
