### ISSUE TITLE
ImportError: cannot import name 'Headers' from 'h11._headers'

### ISSUE THREAD

**Issue by andre-santos1** [mxrch/GHunt#350]
**Describe the bug**
When running GHunt I´m receiving this error: ImportError: cannot import name 'Headers' from 'h11._headers' (/usr/local/lib/python3.10/dist-packages/h11/_headers.py)

**To Reproduce**
1. Go to GHunt folder
2. Run: python3 ghunt.py email <target email>
3. Same error appear when runing: pyhton3 ghunt.py youtube <target channel>
4. Full error below:

osint@osint:~/Programas/ghunt$ python3 ghunt.py email <target email>

Traceback (most recent call last):

  File "/home/osint/Programas/ghunt/ghunt.py", line 12, in <module>

    from modules.email import email_hunt

  File "/home/osint/Programas/ghunt/modules/email.py", line 18, in <module>

    import lib.gmaps as gmaps

  File "/home/osint/Programas/ghunt/lib/gmaps.py", line 8, in <module>

    from seleniumwire import webdriver

  File "/usr/local/lib/python3.10/dist-packages/seleniumwire/webdriver.py", line 27, in <module>

    from seleniumwire import backend, utils

  File "/usr/local/lib/python3.10/dist-packages/seleniumwire/backend.py", line 4, in <module>

    from seleniumwire.server import MitmProxy

  File "/usr/local/lib/python3.10/dist-packages/seleniumwire/server.py", line 7, in <module>

    from seleniumwire.thirdparty.mitmproxy import addons

  File "/usr/local/lib/python3.10/dist-packages/seleniumwire/thirdparty/mitmproxy/addons/__init__.py", line 1, in <module>

    from seleniumwire.thirdparty.mitmproxy.addons import core

  File "/usr/local/lib/python3.10/dist-packages/seleniumwire/thirdparty/mitmproxy/addons/core.py", line 5, in <module>

    from seleniumwire.thirdparty.mitmproxy import command, ctx, exceptions, optmanager, platform

  File "/usr/local/lib/python3.10/dist-packages/seleniumwire/thirdparty/mitmproxy/ctx.py", line 2, in <module>

    import seleniumwire.thirdparty.mitmproxy.master

  File "/usr/local/lib/python3.10/dist-packages/seleniumwire/thirdparty/mitmproxy/master.py", line 7, in <module>

    from seleniumwire.thirdparty.mitmproxy import (

  File "/usr/local/lib/python3.10/dist-packages/seleniumwire/thirdparty/mitmproxy/addonmanager.py", line 8, in <module>

    from seleniumwire.thirdparty.mitmproxy import controller, eventsequence, exceptions

  File "/usr/local/lib/python3.10/dist-packages/seleniumwire/thirdparty/mitmproxy/eventsequence.py", line 3, in <module>

    from seleniumwire.thirdparty.mitmproxy import controller, http, tcp, websocket

  File "/usr/local/lib/python3.10/dist-packages/seleniumwire/thirdparty/mitmproxy/websocket.py", line 5, in <module>

    from wsproto.frame_protocol import CloseReason, Opcode

  File "/usr/local/lib/python3.10/dist-packages/wsproto/__init__.py", line 9, in <module>

    from .connection import Connection, ConnectionState, ConnectionType

  File "/usr/local/lib/python3.10/dist-packages/wsproto/connection.py", line 23, in <module>

    from .utilities import LocalProtocolError

  File "/usr/local/lib/python3.10/dist-packages/wsproto/utilities.py", line 12, in <module>

    from h11._headers import Headers as H11Headers

ImportError: cannot import name 'Headers' from 'h11._headers' (/usr/local/lib/python3.10/dist-packages/h11/_headers.py)

![image](https://user-images.githubusercontent.com/53203402/173583370-9e92473a-0968-4b4c-a809-f7f8a24442ef.png)

**System:**
 - Ubuntu 22.04 LTS
 - Python version 3.10.4

**Comment by nicolasmf** [comment]
Hi, 
Can you run `sudo pip install h11` and show the output ?

**Comment by andre-santos1** [comment]
I solved reinstalling GHunt! \o/
