### ISSUE TITLE
Unable to get cookie.

### ISSUE THREAD

**Issue by OckhamOdyssey** [mxrch/GHunt#355]
**Describe the bug**
Unable to get cookie with a fresh WSL Ubuntu 20.04 LTS install and python3.

**To Reproduce**
1. Clone repo with `python3 -m pip install --upgrade -r requirements.txt`
2. Install pip3 with `sudo apt install pip3`
3. Install requirements has documentation says `python3 -m pip install --upgrade -r requirements.txt`
4. Install Firefox extension has documentation says (https://addons.mozilla.org/es/firefox/addon/ghunt-companion/)
5. Enter drive.google.com or accounts.google.com and get the token
6. Execute token gen with `python3 check_and_gen.py`, select option 2 and paste the base64 cookie.
7. See this:
```
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.9) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
[-] No stored cookies found

You can facilitate configuring GHunt by using the GHunt Companion extension on Firefox, Chrome, Edge and Opera here :
=> https://github.com/mxrch/ghunt_companion

[1] (Companion) Put GHunt on listening mode (currently not compatible with docker)
[2] (Companion) Paste base64-encoded cookies
[3] Enter manually all cookies

Choice => 2
Paste the cookies here => BASE64_TOKEN

[+] The cookies seems valid !
Traceback (most recent call last):
  File "check_and_gen.py", line 218, in <module>
    driver = webdriver.Chrome(
  File "/home/nicolas/.local/lib/python3.8/site-packages/seleniumwire/webdriver.py", line 211, in __init__
    super().__init__(*args, **kwargs)
  File "/home/nicolas/.local/lib/python3.8/site-packages/selenium/webdriver/chrome/webdriver.py", line 69, in __init__
    super().__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "/home/nicolas/.local/lib/python3.8/site-packages/selenium/webdriver/chromium/webdriver.py", line 92, in __init__
    super().__init__(
  File "/home/nicolas/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 277, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/nicolas/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 370, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/nicolas/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 435, in execute
    self.error_handler.check_response(response)
  File "/home/nicolas/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/chromium-browser is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
#0 0x56212c5f9b13 <unknown>
#1 0x56212c400688 <unknown>
#2 0x56212c424f1f <unknown>
#3 0x56212c4205aa <unknown>
#4 0x56212c45b64a <unknown>
#5 0x56212c4557a3 <unknown>
#6 0x56212c42b0ea <unknown>
#7 0x56212c42c225 <unknown>
#8 0x56212c6412dd <unknown>
#9 0x56212c6452c7 <unknown>
#10 0x56212c62b22e <unknown>
#11 0x56212c6460a8 <unknown>
#12 0x56212c61fbc0 <unknown>
#13 0x56212c6626c8 <unknown>
#14 0x56212c662848 <unknown>
#15 0x56212c67cc0d <unknown>
#16 0x7fab8a8ad609 <unknown>
```
**Expected behavior**
Working with no errors, being able to go to the next step.

**System (please complete the following information):**
 - WIndows 11, WSL2, Ubuntu 20.04.4 LTS
 - Python 3.8.10

**Comment by abdalmajid77** [comment]
I get the same problems

**Comment by PnPH** [comment]
I had the same issue, I resolved it installing Chrome
