### ISSUE TITLE
Crash on Play Store Review profile pic link

### ISSUE THREAD

**Issue by Network-Sec** [mxrch/GHunt#362]
`ghunt.py doc https://play-lh.googleusercontent.com/a/AItbvmmNplr21Z[...]`

```python
Document ID : AItbvmmNplr21Z[...]

Traceback (most recent call last):
  File "C:\Users\...\tools\ghunt\ghunt.py", line 40, in <module>
    doc_hunt(data)
  File "C:\Users\...\tools\ghunt\modules\doc.py", line 78, in doc_hunt
    created_date = datetime.strptime(data["createdDate"], '%Y-%m-%dT%H:%M:%S.%fz')
KeyError: 'createdDate'
```
**Everything else works fine!**

Python3.9 on Windows10, requirements.txt installed w/o issue

**Comment by mxrch** [comment]
Hey, it's not supposed to work on Play Store profile pictures 😅
