### ISSUE TITLE
[DEBIAN WSL] Seleniumwire AttributeError

### ISSUE THREAD

**Issue by XFORWORKS** [mxrch/GHunt#364]
It worked perfectly and I set the cookies correctly, but it returned with this issue.
I tried going into the script with 'nano' to check the problem myself and fix it but the thing is that I don't find any flaws in the code...

```
[+] The cookies seems valid !
Traceback (most recent call last):
  File "/mnt/c/Users/krika/ghunt/check_and_gen.py", line 218, in <module>
    driver = webdriver.Chrome(executable_path=driverpath, seleniumwire_options=options, chrome_options=options)
  File "/home/retr0/.local/lib/python3.10/site-packages/seleniumwire/webdriver.py", line 202, in __init__
    chrome_options.add_argument('--proxy-bypass-list=<-loopback>')
AttributeError: 'dict' object has no attribute 'add_argument'
```

Any help or suggestion to fix this issue?
- Retr0

**Comment by rhaby** [comment]
Hey, you
I really want to help you but I can't help you because you have an error in
the file and it could be anywhere in the file so I can't help you without
seeing the file

**Comment by XFORWORKS** [comment]
```
chrome_options = get_chrome_options_args(config.headless)
    options = {
        'connection_timeout': None  # Never timeout, otherwise it floods errors
    }

    tmprinter.out("Starting browser...")
    driver = webdriver.Chrome(executable_path=driverpath, seleniumwire_options=options, chrome_options=options) #This is the only thing I changed
    driver.header_overrides = config.headers

    print("Extracting the tokens...\n")
    # Extracting Google Docs token
    trigger = '\"token\":\"'
    if trigger not in html:
        exit("[-] I can't find the Google Docs token in the source code...\n")
```

I haven't changed anything else in the script but that, to make it easier on the eyes.
If you think I did something wrong, tell me, and thank you for trying to help out.

- Retr0 ( XForWorks )

**Comment by XFORWORKS** [comment]
```
GHunt is listening on port 60067...
[+] Received cookies !

[+] The cookies seems valid !
Traceback (most recent call last):
  File "/mnt/c/Users/<null>/halfalife/attacks/ghunt/check_and_gen.py", line 218, in <module>
    driver = webdriver.Chrome(
  File "/home/<null>/.local/lib/python3.10/site-packages/seleniumwire/webdriver.py", line 217, in __init__
    super().__init__(*args, **kwargs)
  File "/home/<null>/.local/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 69, in __init__
    super().__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "/home/<null>/.local/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py", line 92, in __init__
    super().__init__(
  File "/home/<null>/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 272, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/<null>/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 364, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/<null>/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
  File "/home/<null>/.local/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot find Chrome binary
Stacktrace:
#0 0x7fb0a61d7463 <unknown>
#1 0x7fb0a5f9b8d8 <unknown>
#2 0x7fb0a5fc104a <unknown>
#3 0x7fb0a5fbec05 <unknown>
#4 0x7fb0a6002802 <unknown>
#5 0x7fb0a60022af <unknown>
#6 0x7fb0a5ffa443 <unknown>
#7 0x7fb0a5fcb3c5 <unknown>
#8 0x7fb0a5fcc531 <unknown>
#9 0x7fb0a6229dce <unknown>
#10 0x7fb0a622d192 <unknown>
#11 0x7fb0a620e93e <unknown>
#12 0x7fb0a622e103 <unknown>
#13 0x7fb0a6201d85 <unknown>
#14 0x7fb0a624f0a8 <unknown>
#15 0x7fb0a624f239 <unknown>
#16 0x7fb0a626a492 <unknown>
#17 0x7fb0a54f784a <unknown>
````

I managed to re-download the Repo to show the type of error I am having on WSL.
I haven't learned much about Google Cookies but I can tell that the problem is from the Driver,
It would be greatly appreciated if someone could help me with that problem.

- Retr0 ( XForWorks )

**Comment by mxrch** [comment]
You need Google Chrome.
