### ISSUE TITLE
Missing LSID cookie and error output from check_and_gen.py

### ISSUE THREAD

**Issue by Sha-Gojyo** [mxrch/GHunt#368]
Platform: **Kali linux 2022.3**
Python version: **3.10.7**
_i have not edited any code, just followed the guide._

I tried adding cookies manually, but i do not have an LSID. 
Tried it with the Firefox addon, got detected, it tried to import and gave the exact same error output.

Is the newer Python version really a bottleneck? I can't really downgrade it because it's used by other tools.
Please help me resolve my error.

The error output:
```
[+] The cookies seems valid !
Traceback (most recent call last):
  File "/home/kali/GHunt/check_and_gen.py", line 218, in <module>
    driver = webdriver.Chrome(
  File "/home/kali/.local/lib/python3.10/site-packages/seleniumwire/webdriver.py", line 218, in __init__
    super().__init__(*args, **kwargs)
  File "/home/kali/.local/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 69, in __init__
    super().__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "/home/kali/.local/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py", line 92, in __init__
    super().__init__(
  File "/home/kali/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 272, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/kali/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 364, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/kali/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
  File "/home/kali/.local/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot find Chrome binary
Stacktrace:
#0 0x5556352b32c3 <unknown>
#1 0x5556350bc83a <unknown>
#2 0x5556350df7f4 <unknown>
#3 0x5556350dd546 <unknown>
#4 0x55563511bde6 <unknown>
#5 0x55563511b74f <unknown>
#6 0x555635113d63 <unknown>
#7 0x5556350e87e3 <unknown>
#8 0x5556350e9a21 <unknown>
#9 0x55563530118e <unknown>
#10 0x555635304622 <unknown>
#11 0x5556352e7aae <unknown>
#12 0x5556353052a3 <unknown>
#13 0x5556352dbecf <unknown>
#14 0x555635325588 <unknown>
#15 0x555635325706 <unknown>
#16 0x55563533f8b2 <unknown>
#17 0x7f62cc087b27 <unknown>
```

screendump of cookie overview:
![afbeelding](https://user-images.githubusercontent.com/23507407/193146616-c41c7a00-bc7b-4929-b757-5dcc24f28f6c.png)

**Comment by mxrch** [comment]
Hi, the error says that it doesn't find Chrome.
