### ISSUE TITLE
Google: Error 400: Authentication token must be issued to a non-anonymous app

### ISSUE THREAD

**Issue by MysteriousShadow** [mxrch/GHunt#388]
When I run ghunt in doc mode, the program returned:

```
Traceback (most recent call last):
  File "ghunt.py", line 40, in <module>
    doc_hunt(data)
  File "C:\Users\***\Downloads\GHunt-master\modules\doc.py", line 78, in doc_hunt
    created_date = datetime.strptime(data["createdDate"], '%Y-%m-%dT%H:%M:%S.%fz')
KeyError: 'createdDate'
```

After digging in to the source code, I found the url in which the program is getting. I manually entered that url and google returned:

```
{
  "error": {
    "code": 400,
    "message": "Authentication token must be issued to a non-anonymous app.",
    "errors": [
      {
        "message": "Authentication token must be issued to a non-anonymous app.",
        "domain": "global",
        "reason": "required",
        "location": "authorization",
        "locationType": "header"
      }
    ]
  }
}
```
The cookies were generated with the extension combined with the check_and_gen script.

Any fixes?

**Comment by mxrch** [comment]
Wait until tonight 👀
