### ISSUE TITLE
Login Error: KeyError: 'cookies'

### ISSUE THREAD

**Issue by SSSEAL-C** [mxrch/GHunt#390]
**Describe the bug**
Logging in fails

**To Reproduce**
1. Install ghunt with pipx
2. `ghunt login`
3. Select any option and enter the cookies.

**Expected behavior**
Logging in

**System (please complete the following information):**
 - **OS**: Windows 10.0.19043 Build 19043
 - **Python version**: 3.11.0

**Additional context**
**Traceback**:
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "c:\users\username\.local\bin\ghunt.exe\__main__.py", line 7, in <module>
    sys.exit(main())
             ^^^^^^
  File "C:\Users\username\.local\pipx\venvs\ghunt\Lib\site-packages\ghunt\ghunt.py", line 15, in main
    parse_and_run()
  File "C:\Users\username\.local\pipx\venvs\ghunt\Lib\site-packages\ghunt\cli.py", line 31, in parse_and_run
    process_args(args)
  File "C:\Users\username\.local\pipx\venvs\ghunt\Lib\site-packages\ghunt\cli.py", line 38, in process_args
    trio.run(login.check_and_login, None, args.clean)
  File "C:\Users\username\.local\pipx\venvs\ghunt\Lib\site-packages\trio\_core\_run.py", line 1946, in run
    raise runner.main_task_outcome.error
  File "C:\Users\username\.local\pipx\venvs\ghunt\Lib\site-packages\ghunt\modules\login.py", line 38, in check_and_login
    cookies, oauth_token = await getting_cookies_dialog(wanted_cookies)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\username\.local\pipx\venvs\ghunt\Lib\site-packages\ghunt\helpers\auth.py", line 148, in getting_cookies_dialog
    cookies = data["cookies"]
              ~~~~^^^^^^^^^^^
KeyError: 'cookies'
```

**Comment by mxrch** [comment]
Upgrade your GHunt Companion ;)

**Comment by SSSEAL-C** [comment]
Gotcha, potentially add an error for that? Also nitpick, can you update the Firefox Add-on link to be without default french language, just to auto select based on users language settings? (just remove the `fr/` from the url.)?

**Comment by SSSEAL-C** [comment]
THIS IS BEAUTIFUL HOLY SHIT

**Comment by SSSEAL-C** [comment]
Secondary thing, I am trying to run this within NodeJS using Exec (a bit of a chore I know)

Is there any way to avoid this error?

**Traceback**:
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "c:\users\username\.local\bin\ghunt.exe\__main__.py", line 7, in <module>
  File "C:\Users\username\.local\pipx\venvs\ghunt\Lib\site-packages\ghunt\ghunt.py", line 14, in main
    show_banner()
  File "C:\Users\username\.local\pipx\venvs\ghunt\Lib\site-packages\ghunt\helpers\banner.py", line 19, in show_banner
    gb.rc.print(banner)
  File "C:\Users\username\.local\pipx\venvs\ghunt\Lib\site-packages\rich\console.py", line 1667, in print
    with self:
  File "C:\Users\username\.local\pipx\venvs\ghunt\Lib\site-packages\rich\console.py", line 869, in __exit__
    self._exit_buffer()
  File "C:\Users\username\.local\pipx\venvs\ghunt\Lib\site-packages\rich\console.py", line 827, in _exit_buffer
    self._check_buffer()
  File "C:\Users\username\.local\pipx\venvs\ghunt\Lib\site-packages\rich\console.py", line 2024, in _check_buffer
    legacy_windows_render(buffer, LegacyWindowsTerm(self.file))
  File "C:\Users\username\.local\pipx\venvs\ghunt\Lib\site-packages\rich\_windows_renderer.py", line 17, in legacy_windows_render
    term.write_styled(text, style)
  File "C:\Users\username\.local\pipx\venvs\ghunt\Lib\site-packages\rich\_win32_console.py", line 442, in write_styled
    self.write_text(text)
  File "C:\Users\username\.local\pipx\venvs\ghunt\Lib\site-packages\rich\_win32_console.py", line 403, in write_text
    self.write(text)
  File "C:\Users\username\AppData\Local\Programs\Python\Python311\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f426' in position 11: character maps to <undefined>
```

**Comment by mxrch** [comment]
> Gotcha, potentially add an error for that? Also nitpick, can you update the Firefox Add-on link to be without default french language, just to auto select based on users language settings? (just remove the fr/ from the url.)?

Fixed in https://github.com/mxrch/GHunt/commit/fd5658fb27ff9f4b06b3e2dfb7b0f60875ba2be5

> Secondary thing, I am trying to run this within NodeJS using Exec (a bit of a chore I know)

It seems to be a problem with the Rich library, I don't provide support for use in other languages.
