### ISSUE TITLE
error after installation

### ISSUE THREAD

**Issue by faezakarim** [mxrch/GHunt#395]
**Describe the bug**

I followed instruction for installation exactly. Therefore, after complete installation, while using it is displaying the error below:

[+] Authenticated !
Traceback (most recent call last):
  File "/usr/local/bin/ghunt", line 33, in <module>
    sys.exit(load_entry_point('ghunt==2.0.1', 'console_scripts', 'ghunt')())
  File "/usr/local/lib/python3.10/dist-packages/ghunt-2.0.1-py3.10.egg/ghunt/ghunt.py", line 15, in main
    parse_and_run()
  File "/usr/local/lib/python3.10/dist-packages/ghunt-2.0.1-py3.10.egg/ghunt/cli.py", line 31, in parse_and_run
    process_args(args)
  File "/usr/local/lib/python3.10/dist-packages/ghunt-2.0.1-py3.10.egg/ghunt/cli.py", line 41, in process_args
    trio.run(email.hunt, None, args.email_address, args.json)
  File "/home/student/.local/lib/python3.10/site-packages/trio/_core/_run.py", line 1946, in run
    raise runner.main_task_outcome.error
  File "/usr/local/lib/python3.10/dist-packages/ghunt-2.0.1-py3.10.egg/ghunt/modules/email.py", line 31, in hunt
    is_found, target = await people_pa.people_lookup(as_client, email_address, params_template="max_details")
  File "/usr/local/lib/python3.10/dist-packages/ghunt-2.0.1-py3.10.egg/ghunt/apis/peoplepa.py", line 104, in people_lookup
    await person._scrape(as_client, person_data)
  File "/usr/local/lib/python3.10/dist-packages/ghunt-2.0.1-py3.10.egg/ghunt/parsers/people.py", line 157, in _scrape
    self.profilePhotos[profile_data["metadata"]["container"]] = person_photo
UnboundLocalError: local variable 'profile_data' referenced before assignment

**Comment by mxrch** [comment]
Can you put the error in the body and not the title....

**Comment by mxrch** [comment]
@faezakarim should be fixed in 8f988ab904b1913d98faefc175ebcffd5ec5339e, can you try doing `pipx uninstall ghunt; pipx install git+https://github.com/mxrch/ghunt@8f988ab904b1913d98faefc175ebcffd5ec5339e` retry and tell me if problem is resolved ?

**Comment by faezakarim** [comment]
Thanks bro for responding, it resolved the issue. Yours efforts to develop special tools are appreciable, thanks alot.

**Comment by freestyle3** [comment]
I install ghunt tool but python3 check_and_gen.py command not work 
![Uploading IMG-20231125-WA0001.jpeg…]()
