### ISSUE TITLE
Traceback (most recent call last):

### ISSUE THREAD

**Issue by malos777d** [mxrch/GHunt#397]
Hello guys, 
can you help me with this error?

/ghunt2# ghunt login
_Traceback (most recent call last):
  File "/usr/local/bin/ghunt", line 5, in <module>
    from ghunt.ghunt import main
  File "/usr/local/lib/python3.8/dist-packages/ghunt/__init__.py", line 1, in <module>
    from ghunt import globals as gb; gb.init_globals()
  File "/usr/local/lib/python3.8/dist-packages/ghunt/globals.py", line 5, in init_globals
    from ghunt.objects.utils import TMPrinter
  File "/usr/local/lib/python3.8/dist-packages/ghunt/objects/utils.py", line 1, in <module>
    from ghunt.helpers.utils import *
  File "/usr/local/lib/python3.8/dist-packages/ghunt/helpers/utils.py", line 77, in <module>
    def ppnb(nb: float|int) -> float:
TypeError: unsupported operand type(s) for |: 'type' and 'type'_

Thanks a lot

**Comment by mxrch** [comment]
Hello, duplicated https://github.com/mxrch/GHunt/issues/389 + read the Readme plz
