### ISSUE TITLE
Error when initializing ghunt

### ISSUE THREAD

**Issue by evilapuera** [mxrch/GHunt#398]
Just installed new release of project on my `Ubuntu 20.04.5 LTS`  and got this traceback:
```
Traceback (most recent call last):
  File "/home/evilapuera/.local/bin/ghunt", line 5, in <module>
    from ghunt.ghunt import main
  File "/home/evilapuera/.local/pipx/venvs/ghunt/lib/python3.8/site-packages/ghunt/__init__.py", line 1, in <module>
    from ghunt import globals as gb; gb.init_globals()
  File "/home/evilapuera/.local/pipx/venvs/ghunt/lib/python3.8/site-packages/ghunt/globals.py", line 5, in init_globals
    from ghunt.objects.utils import TMPrinter
  File "/home/evilapuera/.local/pipx/venvs/ghunt/lib/python3.8/site-packages/ghunt/objects/utils.py", line 1, in <module>
    from ghunt.helpers.utils import *
  File "/home/evilapuera/.local/pipx/venvs/ghunt/lib/python3.8/site-packages/ghunt/helpers/utils.py", line 77, in <module>
    def ppnb(nb: float|int) -> float:
TypeError: unsupported operand type(s) for |: 'type' and 'type'
```

**Comment by mxrch** [comment]
You guys are really opening the same issue 2x per day because you can't read the README

<img width="304" alt="image" src="https://user-images.githubusercontent.com/17338428/206225605-eb7422f1-1814-46b2-97cf-c00d26c9473a.png">

**Comment by evilapuera** [comment]
Also python 3.10 installed.

```
python3.10 --version
Python 3.10.9
```

**Comment by mxrch** [comment]
@evilapuera `pipx uninstall ghunt; pipx install ghunt --python $(which python3.10)`
