### ISSUE TITLE
Google Shell Ghunt Installation KeyError "SIDCC"

### ISSUE THREAD

**Issue by i-decrypt** [mxrch/GHunt#422]
I am using google shell with python 3.11.2.  installed ghunt using pipx. i chose method #2 and pasted base64-encoded cookies. now i am getting this error. someone please help me to resolve this. 

🔑 A master token has been generated for your account and saved in the 
credentials file, please keep it safe as if it were your password, because it 
gives access to a lot of Google services, and with that, your personal 
information.
Master token services access : mail, hist, friendview, multilogin, talk, omaha, android, youtube, wise
Generating OSIDs ...
Traceback (most recent call last):
  File "/home/idecrypt/.local/bin/ghunt", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/idecrypt/.local/lib/python3.11/site-packages/ghunt/ghunt.py", line 15, in main
    parse_and_run()
  File "/home/idecrypt/.local/lib/python3.11/site-packages/ghunt/cli.py", line 31, in parse_and_run
    process_args(args)
  File "/home/idecrypt/.local/lib/python3.11/site-packages/ghunt/cli.py", line 38, in process_args
    trio.run(login.check_and_login, None, args.clean)
  File "/home/idecrypt/.local/lib/python3.11/site-packages/trio/_core/_run.py", line 1946, in run
    raise runner.main_task_outcome.error
  File "/home/idecrypt/.local/lib/python3.11/site-packages/ghunt/modules/login.py", line 90, in check_and_login
    ghunt_creds.osids = await gen_osids(cookies, osids)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/idecrypt/.local/lib/python3.11/site-packages/ghunt/helpers/auth.py", line 77, in gen_osids
    sample_cookies[cookie] = req.cookies[cookie]
                             ~~~~~~~~~~~^^^^^^^^
  File "/home/idecrypt/.local/lib/python3.11/site-packages/httpx/_models.py", line 1144, in __getitem__
    raise KeyError(name)
KeyError: 'SIDCC'

**Comment by mxrch** [comment]
Weird

**Comment by mxrch** [comment]
Do you have the last version of GHunt Companion ?
