### ISSUE TITLE
Docker failing on initialization with cookies

### ISSUE THREAD

**Issue by a10kiloham** [mxrch/GHunt#424]
**Describe the bug**
After entering cookies from companion in base64, error logs shows problems with webdriver
```
[Webdrivers Manager] I'm updating the chromedriver...
[Webdrivers Manager] The chromedriver has been updated !

Traceback (most recent call last):
  File "check_and_gen.py", line 211, in <module>
    driver = get_driver(cookies)
  File "check_and_gen.py", line 173, in get_driver
    driver.add_cookie({'name': k, 'value': v, 'domain': '.google.com'})
  File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 751, in add_cookie
    self.execute(Command.ADD_COOKIE, {"cookie": cookie_dict})
  File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 444, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 249, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidArgumentException: Message: invalid argument: missing 'value'
  (Session info: headless chrome=107.0.5304.110)
Stacktrace:
#0 0x55c0860f4463 <unknown>
#1 0x55c085eb88d8 <unknown>
#2 0x55c085f42096 <unknown>
#3 0x55c085f17622 <unknown>
#4 0x55c085f3030f <unknown>
#5 0x55c085f17443 <unknown>
#6 0x55c085ee83c5 <unknown>
#7 0x55c085ee9531 <unknown>
#8 0x55c086146dce <unknown>
#9 0x55c08614a192 <unknown>
#10 0x55c08612b93e <unknown>
#11 0x55c08614b103 <unknown>
#12 0x55c08611ed85 <unknown>
#13 0x55c08616c0a8 <unknown>
#14 0x55c08616c239 <unknown>
#15 0x55c086187492 <unknown>
#16 0x7f57ec32bfa3 start_thread
```

**To Reproduce**
```
sudo docker run -v ghunt-resources:/usr/src/app/resources -ti ghcr.io/mxrch/ghunt:latest check_and_gen.py
```
I paste the base64 blob then.
For help, this is using the Chrome Plugin. The decoded result obj is:
```
{
  "cookies": {
    "APISID": "../..",
    "HSID": "..",
    "LSID": "o.admin.google.com|o.ads.google.com|o.adwords.google.com|o.calendar.google.com|o.chat.google.com|o.console.cloud.google.com|o.docs.google.com|o.domains.google.com|o.drive.google.com|o.fi.google.com|o.gds.google.com|o.groups.google.com|o.lens.google.com|o.mail-settings.google.com|o.mail.google.com|o.meet.google.com|o.myaccount.google.com|o.myactivity.google.com|o.photos.google.com|o.play.google.com|o.script.google.com|s.GB|s.youtube:TwiD1sIEBdzwWuhL091UL4Kz7LxYyIpKLzAUlrEKQQkvi1jor3n4pxqEyYPBmuHQ5YlJkg.",
    "SAPISID": ".../",
    "SID": "....",
    "SSID": "..",
    "__Secure-3PSID": "..."
  },
  "oauth_token": "oauth2_4/..."
}
```
**Expected behavior**

Success

**Screenshots**

**System (please complete the following information):**
 - Ubuntu 22 LTS
 - 
**Additional context**

I can't find the dockerfile to see whether there's some XVFB problem - is there one sourced somewhere?

Thanks for your help!

**Comment by mxrch** [comment]
Hi ! The docker version is no more supported since GHunt v2.
