### ISSUE TITLE
type ghunt login and error

### ISSUE THREAD

**Issue by naufalqwe** [mxrch/GHunt#426]
**Describe the bug**
Traceback (most recent call last):
  File "/root/.local/bin/ghunt", line 5, in <module>
    from ghunt.ghunt import main
  File "/root/.local/pipx/venvs/ghunt/lib/python3.9/site-packages/ghunt/__init__.py", line 1, in <module>
    from ghunt import globals as gb; gb.init_globals()
  File "/root/.local/pipx/venvs/ghunt/lib/python3.9/site-packages/ghunt/globals.py", line 5, in init_globals
    from ghunt.objects.utils import TMPrinter
  File "/root/.local/pipx/venvs/ghunt/lib/python3.9/site-packages/ghunt/objects/utils.py", line 1, in <module>
    from ghunt.helpers.utils import *
  File "/root/.local/pipx/venvs/ghunt/lib/python3.9/site-packages/ghunt/helpers/utils.py", line 77, in <module>
    def ppnb(nb: float|int) -> float:
TypeError: unsupported operand type(s) for |: 'type' and 'type'

**To Reproduce**

**Expected behavior**

**Screenshots**

**System (please complete the following information):**
 - OS
 - Python version

**Additional context**

**Comment by mxrch** [comment]
You don't use Python 3.10+, you don't followed the ReadMe and you don't followed the issue template. I'm closing it.
