### ISSUE TITLE
Having issues starting this up after install

### ISSUE THREAD

**Issue by TejayK1029** [mxrch/GHunt#450]
Just finished downloading and I was trying to get this up with ghunt login and getting this back
Traceback (most recent call last):
  File "/home/kilow/.local/bin/ghunt", line 5, in <module>
    from ghunt.ghunt import main
  File "/home/kilow/.local/pipx/venvs/ghunt/lib/python3.9/site-packages/ghunt/__init__.py", line 1, in <module>
    from ghunt import globals as gb; gb.init_globals()
  File "/home/kilow/.local/pipx/venvs/ghunt/lib/python3.9/site-packages/ghunt/globals.py", line 5, in init_globals
    from ghunt.objects.utils import TMPrinter
  File "/home/kilow/.local/pipx/venvs/ghunt/lib/python3.9/site-packages/ghunt/objects/utils.py", line 1, in <module>
    from ghunt.helpers.utils import *
  File "/home/kilow/.local/pipx/venvs/ghunt/lib/python3.9/site-packages/ghunt/helpers/utils.py", line 77, in <module>
    def ppnb(nb: float|int) -> float:
TypeError: unsupported operand type(s) for |: 'type' and 'type'

Not sure the error, I did fine one solution you had for a previous error
pipx uninstall ghunt; pipx install git+https://github.com/mxrch/ghunt@8f988ab904b1913d98faefc175ebcffd5ec5339e

I tried this as well but still get the same error to no avail.
Any help and a little run down on what the error means would be amazing.

Thank you for all you do

**Comment by JeTondsLeGazon** [comment]
I have the exact same issue with Python 3.8

**Comment by JeTondsLeGazon** [comment]
Actually already discussed [here](https://github.com/mxrch/GHunt/issues/449)

But another error appears when I try with Python 3.11.4:

`ImportError: cannot import name '_imaging' from 'PIL'`

**Comment by Politikkiller** [comment]
> Actually already discussed [here](https://github.com/mxrch/GHunt/issues/449)
> 
> But another error appears when I try with Python 3.11.4:
> 
> `ImportError: cannot import name '_imaging' from 'PIL'`

Are you win this trouble?

**Comment by JeTondsLeGazon** [comment]
Unfortunately no. 

But I more or less gave up ...
