### ISSUE TITLE
Some organization email queries is causing KeyError: 'people'

### ISSUE THREAD

**Issue by juhkarh** [mxrch/GHunt#459]
Hi, I found out there is 'feature' like this. Is some knowhow needed or just good old bug?

Input:
````sh
ghunt email <some organization | association>@gmail.com
````
Result:
````sh
Traceback (most recent call last):
  File "/root/.local/bin/ghunt", line 8, in <module>
    sys.exit(main())
  File "/root/.local/pipx/venvs/ghunt/lib/python3.10/site-packages/ghunt/ghunt.py", line 15, in main
    parse_and_run()
  File "/root/.local/pipx/venvs/ghunt/lib/python3.10/site-packages/ghunt/cli.py", line 31, in parse_and_run
    process_args(args)
  File "/root/.local/pipx/venvs/ghunt/lib/python3.10/site-packages/ghunt/cli.py", line 41, in process_args
    trio.run(email.hunt, None, args.email_address, args.json)
  File "/root/.local/pipx/venvs/ghunt/lib/python3.10/site-packages/trio/_core/_run.py", line 1946, in run
    raise runner.main_task_outcome.error
  File "/root/.local/pipx/venvs/ghunt/lib/python3.10/site-packages/ghunt/modules/email.py", line 31, in hunt
    is_found, target = await people_pa.people_lookup(as_client, email_address, params_template="max_details")
  File "/root/.local/pipx/venvs/ghunt/lib/python3.10/site-packages/ghunt/apis/peoplepa.py", line 103, in people_lookup
    person_data = list(data["people"].values())[0]
KeyError: 'people'
````

OS:  
-  Docker container - base image `python:3.10`

I cannot give a email for testing.. OPSEC  😉

**Comment by bhavna3** [comment]
its a bug in the script, examine the code of the ghunt script to identify and fix the issue.

**Comment by juhkarh** [comment]
It might be possible that there was some authentication problems in background.

**Comment by pranali18-Ai** [comment]
The error message indicates that the "ghunt" tool couldn't find a specific piece of information labeled 'people' in the data it was trying to use. This could be happening for a few different reasons. It might be due to a problem with the source of the data or because the email address you provided is incorrect or not in the expected format.

To fix this issue, you should first verify that the email address you entered is accurate and follows the correct format. It's also a good idea to make sure that the "ghunt" tool you're using is up-to-date. There could be known issues or updates related to the tool that need to be addressed for it to work correctly.

**Comment by mxrch** [comment]
@pranali18-Ai wtf is that useless ChatGPT reply

**Comment by juhkarh** [comment]
> Did you guys find a fix for it? I am facing the same problem.

I haven't had time for this. 
But maybe someone can add some try..except logic around this `person_data = list(data["people"].values())[0]`.
Its very error prone to make this kind of assumptions in code that is consuming external api.

**Comment by eqa** [comment]
{'error': {'code': 400, 'message': 'Request contains an invalid argument.', 'status': 'INVALID_ARGUMENT'}}

and the argument you must crop from the request is : 

https://github.com/mxrch/GHunt/blob/7042aa0f4664b273e6f8748710c0b8d06890934c/ghunt/apis/peoplepa.py#L60
"GPLUS_ADDITIONAL_DATA"

**Comment by iKey-333** [comment]
for some reason, the request req = `await self._query(as_client, verb, endpoint_name, base_url, params_templates[params_template], None, data_type)` began to produce **<Response [400 Bad Request]>** instead of json

With what it can be connected?

**Comment by iKey-333** [comment]
> Google invalided the `GPLUS_ADDITIONAL_DATA` param, please `pipx upgrade ghunt` :)

please tell me what this parameter was responsible for? What information are we now deprived of?

**Comment by juhkarh** [comment]
`KeyError: 'people'`
This error was fixed in latest release. It was about changes at Google side.

**Comment by GalaadSubileau** [comment]
Same error here. I am up-to-date. 

Looks like this other issue that has been fixed: https://github.com/mxrch/GHunt/issues/459.
Which was apparently about a change on Google's side (changing the value of "GPLUS_ADDITIONAL_DATA" used in the file: GHunt/ghunt/apis/peoplepa.py).


If necessary, here is my shell output:
```sh
$ pipx upgrade ghunt
ghunt is already at latest version 2.2.2 (location: /home/[REDACTED]/.local/share/pipx/venvs/ghunt)

$ ghunt email [REDACTED]@gmail.com

     .d8888b.  888    888                   888
    d88P  Y88b 888    888                   888
    888    888 888    888                   888
    888        8888888888 888  888 88888b.  888888
    888  88888 888    888 888  888 888 "88b 888
    888    888 888    888 888  888 888  888 888
    Y88b  d88P 888    888 Y88b 888 888  888 Y88b.
     "Y8888P88 888    888  "Y88888 888  888  "Y888 v2

             By: mxrch (🐦 @mxrchreborn)
       Support my work on GitHub Sponsors ! 💖


         > GHunt 2.2.2 (Wardriving Edition) <

🎉 You are up to date !

[+] Stored session loaded !
[+] Authenticated !

Traceback (most recent call last):
  File "/home/sdev/.local/bin/ghunt", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/sdev/.local/share/pipx/venvs/ghunt/lib/python3.12/site-packages/ghunt/ghunt.py", line 18, in main
    parse_and_run()
  File "/home/sdev/.local/share/pipx/venvs/ghunt/lib/python3.12/site-packages/ghunt/cli.py", line 55, in parse_and_run
    process_args(args)
  File "/home/sdev/.local/share/pipx/venvs/ghunt/lib/python3.12/site-packages/ghunt/cli.py", line 65, in process_args
    asyncio.run(email.hunt(None, args.email_address, args.json))
  File "/usr/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/sdev/.local/share/pipx/venvs/ghunt/lib/python3.12/site-packages/ghunt/modules/email.py", line 25, in hunt
    is_found, target = await people_pa.people_lookup(as_client, email_address, params_template="max_details")
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sdev/.local/share/pipx/venvs/ghunt/lib/python3.12/site-packages/ghunt/apis/peoplepa.py", line 111, in people_lookup
    person_data = list(data["people"].values())[0]
                       ~~~~^^^^^^^^^^
KeyError: 'people'
```

**Comment by KaKi87** [comment]
Hi,

I'm still experiencing this issue despite being up to date :

```
         > GHunt 2.3.3 (🕷️  Spider Edition) <
🎉 You are up to date !
[+] Stored session loaded !
[+] Authenticated !
Traceback (most recent call last):
  File "/home/kaki/.local/bin/ghunt", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/kaki/.local/pipx/venvs/ghunt/lib/python3.11/site-packages/ghunt/ghunt.py", line 18, in main
    parse_and_run()
  File "/home/kaki/.local/pipx/venvs/ghunt/lib/python3.11/site-packages/ghunt/cli.py", line 63, in parse_and_run
    process_args(args)
  File "/home/kaki/.local/pipx/venvs/ghunt/lib/python3.11/site-packages/ghunt/cli.py", line 73, in process_args
    asyncio.run(email.hunt(None, args.email_address, args.json))
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/kaki/.local/pipx/venvs/ghunt/lib/python3.11/site-packages/ghunt/modules/email.py", line 25, in hunt
    is_found, target = await people_pa.people_lookup(as_client, email_address, params_template="max_details")
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kaki/.local/pipx/venvs/ghunt/lib/python3.11/site-packages/ghunt/apis/peoplepa.py", line 120, in people_lookup
    person_data = list(data["people"].values())[0]
                       ~~~~^^^^^^^^^^
KeyError: 'people'
```

Thanks
