### ISSUE TITLE
Python Crash on Mac OS

### ISSUE THREAD

**Issue by matthew2848123** [mxrch/GHunt#462]
**Describe the bug**
/.local/pipx/venvs/ghunt/lib/python3.9/site-packages/ghunt/helpers/utils.py", line 77, in <module>
    def ppnb(nb: float|int) -> float:
**To Reproduce**
1. Open Terminal
2. Type ghunt
3. Crash

**Expected behavior**

**Screenshots**

**System (please complete the following information):**
 - OS 13.0 (22A380)
 - Python version 3.9

**Additional context**

**Comment by DannyCork** [comment]
same on Samona 14.4 (23E214) using Python 3.12.2

```

$ ghunt login
Traceback (most recent call last):
  File "/Users/d/.local/bin/ghunt", line 7, in <module>
    from ghunt.ghunt import main
  File "/Users/d/Library/Application Support/pipx/venvs/ghunt/lib/python3.9/site-packages/ghunt/__init__.py", line 1, in <module>
    from ghunt import globals as gb; gb.init_globals()
  File "/Users/d/Library/Application Support/pipx/venvs/ghunt/lib/python3.9/site-packages/ghunt/globals.py", line 5, in init_globals
    from ghunt.objects.utils import TMPrinter
  File "/Users/d/Library/Application Support/pipx/venvs/ghunt/lib/python3.9/site-packages/ghunt/objects/utils.py", line 1, in <module>
    from ghunt.helpers.utils import *
  File "/Users/d/Library/Application Support/pipx/venvs/ghunt/lib/python3.9/site-packages/ghunt/helpers/utils.py", line 77, in <module>
    def ppnb(nb: float|int) -> float:
```
