### ISSUE TITLE
Bug founded

### ISSUE THREAD

**Issue by Shoukaku07** [mxrch/GHunt#470]
root@WIN-6USDKMQTSI2:/home/Shoukaku07/GHunt# python3 main.py gaia xxxxxxxxxxxxxxx

     .d8888b.  888    888                   888
    d88P  Y88b 888    888                   888
    888    888 888    888                   888
    888        8888888888 888  888 88888b.  888888
    888  88888 888    888 888  888 888 "88b 888
    888    888 888    888 888  888 888  888 888
    Y88b  d88P 888    888 Y88b 888 888  888 Y88b.
     "Y8888P88 888    888  "Y88888 888  888  "Y888 v2

             By: mxrch (🐦 @mxrchreborn)
       Support my work on GitHub Sponsors ! 💖

[+] Authenticated !
Traceback (most recent call last):
  File "/home/shoukaku07/GHunt/main.py", line 2, in <module>
    from ghunt import ghunt; ghunt.main()
  File "/home/shoukaku07/GHunt/ghunt/ghunt.py", line 15, in main
    parse_and_run()
  File "/home/shoukaku07/GHunt/ghunt/cli.py", line 31, in parse_and_run
    process_args(args)
  File "/home/shoukaku07/GHunt/ghunt/cli.py", line 44, in process_args
    trio.run(gaia.hunt, None, args.gaia_id, args.json)
  File "/usr/local/lib/python3.10/dist-packages/trio/_core/_run.py", line 1946, in run
    raise runner.main_task_outcome.error
  File "/home/shoukaku07/GHunt/ghunt/modules/gaia.py", line 28, in hunt
    is_found, target = await people_pa.people(as_client, gaia_id, params_template="max_details")
  File "/home/shoukaku07/GHunt/ghunt/apis/peoplepa.py", line 165, in people
    if data["personResponse"][0]["status"] == "NOT_FOUND":
KeyError: 'personResponse'

**Comment by lpi-code** [comment]
Same thing here
/v2/people respond with :
`{'error': {'code': 400, 'message': 'Request contains an invalid argument.', 'status': 'INVALID_ARGUMENT'}}`

**Comment by mythdotrip** [comment]
This is due to your params_template being set to max_details.
max_details currently has a bug.

I suggest using "just_name" instead of "max_details" until mxrch has pushed a fix.

**Comment by Shoukaku07** [comment]
> This is due to your params_template being set to max_details. max_details currently has a bug.
> 
> I suggest using "just_name" instead of "max_details" until mxrch has pushed a fix.

thx
