### ISSUE TITLE
bug when using email option

### ISSUE THREAD

**Issue by Kilimignon** [mxrch/GHunt#471]
**Describe the bug**
i tried to lookup infos of an email.
**To Reproduce**
basically downloaded ghunt and all the other stuff, put in cookies and tried to _ghunt email <email>_

**Expected behavior**
show infos abt the amil

**What it actually did**

Traceback (most recent call last):
  File "C:\Users\GPT\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\GPT\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\GPT\AppData\Local\Programs\Python\Python310\Scripts\ghunt.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "C:\Users\GPT\AppData\Local\Programs\Python\Python310\lib\site-packages\ghunt\ghunt.py", line 15, in main
    parse_and_run()
  File "C:\Users\GPT\AppData\Local\Programs\Python\Python310\lib\site-packages\ghunt\cli.py", line 31, in parse_and_run
    process_args(args)
  File "C:\Users\GPT\AppData\Local\Programs\Python\Python310\lib\site-packages\ghunt\cli.py", line 41, in process_args
    trio.run(email.hunt, None, args.email_address, args.json)
  File "C:\Users\GPT\AppData\Local\Programs\Python\Python310\lib\site-packages\trio\_core\_run.py", line 1946, in run
    raise runner.main_task_outcome.error
  File "C:\Users\GPT\AppData\Local\Programs\Python\Python310\lib\site-packages\ghunt\modules\email.py", line 31, in hunt
    is_found, target = await people_pa.people_lookup(as_client, email_address, params_template="max_details")
  File "C:\Users\GPT\AppData\Local\Programs\Python\Python310\lib\site-packages\ghunt\apis\peoplepa.py", line 103, in people_lookup
    person_data = list(data["people"].values())[0]
KeyError: 'people'

**Comment by ItsMalware** [comment]
having this same issue.

**Comment by mythdotrip** [comment]
This is due to your params_template being set to max_details.
max_details currently has a bug.

I suggest using "just_name" instead of "max_details" until mxrch has pushed a fix.

**Comment by xdTAGCLAN** [comment]
> This is due to your params_template being set to max_details. max_details currently has a bug.
> 
> I suggest using "just_name" instead of "max_details" until mxrch has pushed a fix.

Where do I do this?
