### ISSUE TITLE
Problem when load coockies.

### ISSUE THREAD

**Issue by mmsouto81** [mxrch/GHunt#49]
Hi, I have a problem loading cookies. I run check_and_gen.py and when it asks for each of the cookies I paste them without the quotes and when I enter the last one it gives me these errors.

========================================================
Traceback (most recent call last):
  File "C: \ Python \ lib \ site-packages \ httpx \ _exceptions.py", line 339, in map_exceptions
    yield
  File "C: \ Python \ lib \ site-packages \ httpx \ _client.py", line 854, in _send_single_request
    (status_code, headers, stream, ext) = transport.request (
  File "C: \ Python \ lib \ site-packages \ httpcore \ _sync \ connection_pool.py", line 200, in request
    response = connection.request (
  File "C: \ Python \ lib \ site-packages \ httpcore \ _sync \ connection.py", line 100, in request
    return self.connection.request (method, url, headers, stream, ext)
  File "C: \ Python \ lib \ site-packages \ httpcore \ _sync \ http11.py", line 72, in request
    ) = self._receive_response (timeout)
  File "C: \ Python \ lib \ site-packages \ httpcore \ _sync \ http11.py", line 133, in _receive_response
    event = self._receive_event (timeout)
  File "C: \ Python \ lib \ site-packages \ httpcore \ _sync \ http11.py", line 163, in _receive_event
    data = self.socket.read (self.READ_NUM_BYTES, timeout)
  File "C: \ Python \ lib \ site-packages \ httpcore \ _backends \ sync.py", line 62, in read
    return self.sock.recv (n)
  File "C: \ Python \ lib \ contextlib.py", line 131, in __exit__
    self.gen.throw (type, value, traceback)
  File "C: \ Python \ lib \ site-packages \ httpcore \ _exceptions.py", line 12, in map_exceptions
    raise to_exc (exc) from None
httpcore.ReadTimeout: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C: \ Python \ GHunt \ check_and_gen.py", line 38, in <module>
    req = httpx.get ("https://docs.google.com/document/u/0/?usp=direct_url", cookies = cookies, headers = headers,
  File "C: \ Python \ lib \ site-packages \ httpx \ _api.py", line 181, in get
    return request (
  File "C: \ Python \ lib \ site-packages \ httpx \ _api.py", line 93, in request
    return client.request (
  File "C: \ Python \ lib \ site-packages \ httpx \ _client.py", line 721, in request
    return self.send (
  File "C: \ Python \ lib \ site-packages \ httpx \ _client.py", line 753, in send
    response = self._send_handling_auth (
  File "C: \ Python \ lib \ site-packages \ httpx \ _client.py", line 791, in _send_handling_auth
    response = self._send_handling_redirects (
  File "C: \ Python \ lib \ site-packages \ httpx \ _client.py", line 823, in _send_handling_redirects
    response = self._send_single_request (request, timeout)
  File "C: \ Python \ lib \ site-packages \ httpx \ _client.py", line 854, in _send_single_request
    (status_code, headers, stream, ext) = transport.request (
  File "C: \ Python \ lib \ contextlib.py", line 131, in __exit__
    self.gen.throw (type, value, traceback)
  File "C: \ Python \ lib \ site-packages \ httpx \ _exceptions.py", line 356, in map_exceptions
    raise mapped_exc (message, ** kwargs) from exc # type: ignore
httpx.ReadTimeout: The read operation timed out

**Comment by mxrch** [comment]
@mmsouto81 on line 34, can you change the line `client = httpx.Client(cookies=cookies)` by `client = httpx.Client(cookies=cookies, timeout=20)` and tell me what it does ?
