### ISSUE TITLE
Doesn't work!(

### ISSUE THREAD

**Issue by cryptobesikairdrops01** [mxrch/GHunt#492]
After installation as written in the manual and at startup - errors are displayed and won't start! Doesn't work!(
![Screenshot_2](https://github.com/mxrch/GHunt/assets/157757711/e429bc07-b105-483f-a155-64b055cc7dea)

**Comment by shion1305** [comment]
Hi,
I've looked into the problem and found that some exceptions are not handled correctly.
It looks like GHunt failed to handle `GHuntAndroidAppOAuth2Error` in the following code. https://github.com/mxrch/GHunt/blob/f37efa4b81d447733f34fd93e4840b66e83c9b8d/ghunt/modules/login.py#L31-L35

I'll make a PR that fixes this part.

**Comment by mxrch** [comment]
> Hi, I've looked into the problem and found that some exceptions are not handled correctly. It looks like GHunt failed to handle `GHuntAndroidAppOAuth2Error` in the following code.
> 
> https://github.com/mxrch/GHunt/blob/f37efa4b81d447733f34fd93e4840b66e83c9b8d/ghunt/modules/login.py#L31-L35
> 
> I'll make a PR that fixes this part.

@shion1305 the GHuntAndroidAppOAuth2Error already abstracts the error, and it means what the errors means, that the OAuth2 connection failed. We'll not abstract an abstraction.
The real issue here is that the OAuth2 connection failed, but I can't help with that because I can't reproduce and never had this issue.

@cryptobesikairdrops01 Can you retry with another Google account ?

**Comment by shion1305** [comment]
@mxrch
I think he is saying that he cannot enter login option selection, because `ghunt login` keeps failing before he can select an authentication method. 

I don't think `GHuntInvalidSession` will handle `GHuntAndroidAppOAuth2Error`, as the definitions of `GHuntInvalidSession` and `GHuntAndroidAppOAuth2Error` are the following...
https://github.com/mxrch/GHunt/blob/f37efa4b81d447733f34fd93e4840b66e83c9b8d/ghunt/errors.py#L31-L41

In fact, if you change the code as follows, `python main.py login` will always fail.
```python
    try:
        ghunt_creds = await auth.load_and_auth(as_client, help=False)
        raise GHuntAndroidAppOAuth2Error("!!!!!!!!!!!!!")
    except GHuntInvalidSession as e:
        print(f"[-] {e}\n")
        is_session_valid = False
```
![image](https://github.com/mxrch/GHunt/assets/20254962/efacabd6-1e69-48e1-b55c-bc7ede2f5bf2)

I've confirmed the fix in #493 , plz check it 🙏

**Comment by mxrch** [comment]
I really think that's the an error related to the Google Account, not GHunt.

In fact, the master token can expire if you change the password. @cryptobesikairdrops01 is it the case ?
You can try `ghunt login --clean` and re-login.

**Comment by shion1305** [comment]
@mxrch You're right that the error is due to the Google Account, but I'm saying that users should easily recover from the situation, though GHunt should handle the error and let user know what is the problem.

In @cryptobesikairdrops01 case, running GHunt login leads to an error that prevents further authentication steps, and is it difficult for users that they should use `--clean` option.

To make it more user-friendly, I've submitted PR  #494 , proposing a way to handle errors that guides users to re-authenticate instead of abruptly stopping the program.

Thanks for considering my suggestion.

**Comment by cryptobesikairdrops01** [comment]
> I really think that's the an error related to the Google Account, not GHunt.
> 
> In fact, the master token can expire if you change the password. @cryptobesikairdrops01 is it the case ? Also, can you can try `ghunt login --clean` and re-login ?



> @mxrch You're right that the error is due to the Google Account, but I'm saying that users should be able to know the cause and recover from it easily, though GHunt should handle the error and let user know what is the problem.
> 
> In @cryptobesikairdrops01 case, running GHunt login leads to an error that prevents further authentication steps, and is it difficult for users to know that they should use `--clean` option.
> 
> To make it more user-friendly, I've submitted PR #494 , proposing a way to handle errors that guides users to re-authenticate instead of abruptly stopping the program.
> 
> Thanks for considering my suggestion.

Thank you! It worked.

**Comment by cryptobesikairdrops01** [comment]
I didn't know about the --clean option.
Thank you!

**Comment by albotroz** [comment]
It is still not working for me.
Ghunt only worked very briefly (1-2 days) about a week ago and has not been usable since then because error messages are constantly being displayed. Even with the update.

**Comment by mxrch** [comment]
> It is still not working for me.
> Ghunt only worked very briefly (1-2 days) about a week ago and has not been usable since then because error messages are constantly being displayed. Even with the update.

Even with the latest update, from yesterday ?

**Comment by albotroz** [comment]
> > It is still not working for me.
> > Ghunt only worked very briefly (1-2 days) about a week ago and has not been usable since then because error messages are constantly being displayed. Even with the update.
> 
> Even with the latest update, from yesterday ?

yes.
```
🎉 You are up to date !

[+] Stored session loaded !
[+] Authenticated !

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "c:\users\sdf\.local\bin\ghunt.exe\__main__.py", line 7, in <module>
  File "C:\Users\sdf\AppData\Local\pipx\pipx\venvs\ghunt\Lib\site-packages\ghunt\ghunt.py", line 18, in main
    parse_and_run()
  File "C:\Users\sdf\AppData\Local\pipx\pipx\venvs\ghunt\Lib\site-packages\ghunt\cli.py", line 31, in parse_and_run
    process_args(args)
  File "C:\Users\sdf\AppData\Local\pipx\pipx\venvs\ghunt\Lib\site-packages\ghunt\cli.py", line 41, in process_args
    asyncio.run(email.hunt(None, args.email_address, args.json))
  File "C:\Users\sdf\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\sdf\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sdf\Python\Python311\Lib\asyncio\base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\sdf\AppData\Local\pipx\pipx\venvs\ghunt\Lib\site-packages\ghunt\modules\email.py", line 24, in hunt
    is_found, target = await people_pa.people_lookup(as_client, email_address, params_template="max_details")
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sdf\AppData\Local\pipx\pipx\venvs\ghunt\Lib\site-packages\ghunt\apis\peoplepa.py", line 103, in people_lookup
    person_data = list(data["people"].values())[0]
                       ~~~~^^^^^^^^^^
KeyError: 'people'
```
