### ISSUE TITLE
Maps analysis causes systematic error

### ISSUE THREAD

**Issue by unguest** [mxrch/GHunt#500]
**Describe the bug**

**To Reproduce**
1. Launch any email analysis

**Expected behavior**
Having an analysis of Maps contributions.

**Trace**
```bash
Traceback (most recent call last):
  File "/Users/unguest/.local/bin/ghunt", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/unguest/Library/Application Support/pipx/venvs/ghunt/lib/python3.12/site-packages/ghunt/ghunt.py", line 18, in main
    parse_and_run()
  File "/Users/unguest/Library/Application Support/pipx/venvs/ghunt/lib/python3.12/site-packages/ghunt/cli.py", line 31, in parse_and_run
    process_args(args)
  File "/Users/unguest/Library/Application Support/pipx/venvs/ghunt/lib/python3.12/site-packages/ghunt/cli.py", line 41, in process_args
    asyncio.run(email.hunt(None, args.email_address, args.json))
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/base_events.py", line 664, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/unguest/Library/Application Support/pipx/venvs/ghunt/lib/python3.12/site-packages/ghunt/modules/email.py", line 116, in hunt
    err, stats, reviews, photos = await gmaps.get_reviews(as_client, target.personId)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/unguest/Library/Application Support/pipx/venvs/ghunt/lib/python3.12/site-packages/ghunt/helpers/gmaps.py", line 88, in get_reviews
    review.id = review_data[0][10]
                ~~~~~~~~~~~~~~^^^^
TypeError: 'NoneType' object is not subscriptable
```

**System (please complete the following information):**
 - OSX
 - Python3.12

**Additional context**
Maybe something changed in Maps' pages architecture ?

**Comment by mxrch** [comment]
I confirm the bug, Google changed something. I'm on it

**Comment by mxrch** [comment]
Fixed, please `pipx upgrade ghunt`.

**Comment by Aadithyavarnam** [comment]
馃椇锔� Maps data
Traceback (most recent call last):
  File "/var/www/html/osint.rocks/venv/bin/ghunt", line 8, in 
    sys.exit(main())
             ^^^^^^
  File "/var/www/html/osint.rocks/venv/lib/python3.11/site-packages/ghunt/ghunt.py", line 18, in main
    parse_and_run()
  File "/var/www/html/osint.rocks/venv/lib/python3.11/site-packages/ghunt/cli.py", line 63, in parse_and_run
    process_args(args)
  File "/var/www/html/osint.rocks/venv/lib/python3.11/site-packages/ghunt/cli.py", line 73, in process_args
    asyncio.run(email.hunt(None, args.email_address, args.json))
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/var/www/html/osint.rocks/venv/lib/python3.11/site-packages/ghunt/modules/email.py", line 117, in hunt
    err, stats, reviews, photos = await gmaps.get_reviews(as_client, target.personId)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/www/html/osint.rocks/venv/lib/python3.11/site-packages/ghunt/helpers/gmaps.py", line 59, in get_reviews
    data = json.loads(req.text[5:])
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
