### ISSUE TITLE
Plenty of errors

### ISSUE THREAD

**Issue by albotroz** [mxrch/GHunt#505]
**Describe the bug**
```
🎉 You are up to date !

[+] Stored session loaded !
[+] Authenticated !

🙋 Google Account data

Name : The User

[+] Custom profile picture !
=> https://lh3.googleusercontent.com/
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "c:\users\PC\.local\bin\ghunt.exe\__main__.py", line 7, in <module>
  File "C:\Users\PC\AppData\Local\pipx\pipx\venvs\ghunt\Lib\site-packages\ghunt\ghunt.py", line 18, in main
    parse_and_run()
  File "C:\Users\PC\AppData\Local\pipx\pipx\venvs\ghunt\Lib\site-packages\ghunt\cli.py", line 31, in parse_and_run
    process_args(args)
  File "C:\Users\PC\AppData\Local\pipx\pipx\venvs\ghunt\Lib\site-packages\ghunt\cli.py", line 41, in process_args
    asyncio.run(email.hunt(None, args.email_address, args.json))
  File "C:\Users\PC\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\PC\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\Python\Python311\Lib\asyncio\base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\PC\AppData\Local\pipx\pipx\venvs\ghunt\Lib\site-packages\ghunt\modules\email.py", line 55, in hunt
    await ia.detect_face(vision_api, as_client, target.profilePhotos[container].url)
  File "C:\Users\PC\AppData\Local\pipx\pipx\venvs\ghunt\Lib\site-packages\ghunt\helpers\ia.py", line 18, in detect_face
    rate_limited, are_faces_found, faces_results = await vision_api.detect_faces(as_client, image_content=encoded_image)
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\AppData\Local\pipx\pipx\venvs\ghunt\Lib\site-packages\ghunt\apis\vision.py", line 91, in detect_faces
    data = json.loads(req.text)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\Python\Python311\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\Python\Python311\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\Python\Python311\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**System (please complete the following information):**
 - OS
 - Win 10 x64
 - Python version
 - 3.11.8 x64

Tried with --clean.
Using it behind VPN.

**Comment by mxrch** [comment]
Fixed
