### ISSUE TITLE
KeyError: 'people' on 3 different accounts

### ISSUE THREAD

**Issue by 2ir** [mxrch/GHunt#513]
I tried 3 different accounts but I'm always getting `KeyError: 'people'`. 

 - OS: arch linux
 - Python version: 3.11.8

```
[caio@archlinux ~]$ ghunt email larry@google.com

     .d8888b.  888    888                   888    
    d88P  Y88b 888    888                   888    
    888    888 888    888                   888    
    888        8888888888 888  888 88888b.  888888 
    888  88888 888    888 888  888 888 "88b 888    
    888    888 888    888 888  888 888  888 888    
    Y88b  d88P 888    888 Y88b 888 888  888 Y88b.  
     "Y8888P88 888    888  "Y88888 888  888  "Y888 v2

             By: mxrch (🐦 @mxrchreborn)
       Support my work on GitHub Sponsors ! 💖
    

          > GHunt 2.1.3 (BlackHat Edition) <         

🎉 You are up to date !

[+] Stored session loaded !
[+] Authenticated !

Traceback (most recent call last):
  File "/home/caio/.local/bin/ghunt", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/caio/.local/share/pipx/venvs/ghunt/lib/python3.11/site-packages/ghunt/ghunt.py", line 18, in main
    parse_and_run()
  File "/home/caio/.local/share/pipx/venvs/ghunt/lib/python3.11/site-packages/ghunt/cli.py", line 31, in parse_and_run
    process_args(args)
  File "/home/caio/.local/share/pipx/venvs/ghunt/lib/python3.11/site-packages/ghunt/cli.py", line 41, in process_args
    asyncio.run(email.hunt(None, args.email_address, args.json))
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/caio/.local/share/pipx/venvs/ghunt/lib/python3.11/site-packages/ghunt/modules/email.py", line 24, in hunt
    is_found, target = await people_pa.people_lookup(as_client, email_address, params_template="max_details")
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/caio/.local/share/pipx/venvs/ghunt/lib/python3.11/site-packages/ghunt/apis/peoplepa.py", line 103, in people_lookup
    person_data = list(data["people"].values())[0]
                       ~~~~^^^^^^^^^^
KeyError: 'people'
```

**Comment by techandlaw** [comment]
+1

**Comment by StigP1337** [comment]
Is it possible to see from the "Master token services access" list, if the account will work? Which mandatory services must be in the list? I tried with two accounts which didn't work. Same error as above when I try to query an email address. Both have different services in the list: "hist, mail, talk, cl, multilogin, youtube" and "mail, friendview, talk, android".

**Comment by E5GEN2** [comment]
I am having this error

**Comment by GalaadSubileau** [comment]
Same error here. I am up-to-date. 

Looks like this other issue that has been fixed: https://github.com/mxrch/GHunt/issues/459.
Which was apparently about a change on Google's side (changing the value of "GPLUS_ADDITIONAL_DATA" used in the file: GHunt/ghunt/apis/peoplepa.py).


If necessary, here is my shell output:
```sh
$ pipx upgrade ghunt
ghunt is already at latest version 2.2.2 (location: /home/[REDACTED]/.local/share/pipx/venvs/ghunt)

$ ghunt email [REDACTED]@gmail.com

     .d8888b.  888    888                   888
    d88P  Y88b 888    888                   888
    888    888 888    888                   888
    888        8888888888 888  888 88888b.  888888
    888  88888 888    888 888  888 888 "88b 888
    888    888 888    888 888  888 888  888 888
    Y88b  d88P 888    888 Y88b 888 888  888 Y88b.
     "Y8888P88 888    888  "Y88888 888  888  "Y888 v2

             By: mxrch (🐦 @mxrchreborn)
       Support my work on GitHub Sponsors ! 💖


         > GHunt 2.2.2 (Wardriving Edition) <

🎉 You are up to date !

[+] Stored session loaded !
[+] Authenticated !

Traceback (most recent call last):
  File "/home/sdev/.local/bin/ghunt", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/sdev/.local/share/pipx/venvs/ghunt/lib/python3.12/site-packages/ghunt/ghunt.py", line 18, in main
    parse_and_run()
  File "/home/sdev/.local/share/pipx/venvs/ghunt/lib/python3.12/site-packages/ghunt/cli.py", line 55, in parse_and_run
    process_args(args)
  File "/home/sdev/.local/share/pipx/venvs/ghunt/lib/python3.12/site-packages/ghunt/cli.py", line 65, in process_args
    asyncio.run(email.hunt(None, args.email_address, args.json))
  File "/usr/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/sdev/.local/share/pipx/venvs/ghunt/lib/python3.12/site-packages/ghunt/modules/email.py", line 25, in hunt
    is_found, target = await people_pa.people_lookup(as_client, email_address, params_template="max_details")
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sdev/.local/share/pipx/venvs/ghunt/lib/python3.12/site-packages/ghunt/apis/peoplepa.py", line 111, in people_lookup
    person_data = list(data["people"].values())[0]
                       ~~~~^^^^^^^^^^
KeyError: 'people'
```

**Comment by piranhap** [comment]
Hi, I'm having the same issue. Currently on 2.2.2

**Comment by Nem0oo** [comment]
Hi, it seems like the error is actually related to the authentication.
in peoplepa.py around line 120 we try 
`person_data = list(data["people"].values())[0]`

the error state that  "people" is not a valid key so I printed the content of data, and I got this : 
`{'error': {'code': 401, 'message': 'Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.', 'status': 'UNAUTHENTICATED'}`

Got it to work after 7 try of logging in. It seems like google is revoking the creds as it consider them as suspicious activity

**Comment by calinux-py** [comment]
> Hi, it seems like the error is actually related to the authentication. in peoplepa.py around line 120 we try `person_data = list(data["people"].values())[0]`
> 
> the error state that "people" is not a valid key so I printed the content of data, and I got this : `{'error': {'code': 401, 'message': 'Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.', 'status': 'UNAUTHENTICATED'}`
> 
> Got it to work after 7 try of logging in. It seems like google is revoking the creds as it consider them as suspicious activity

THIS WORKED! THANK YOU

**Comment by ShadowJonathan** [comment]
Ditto, google simply kicked me out of the service before I could use it.

I'd recommend adding a check to see if the master token (and the likes) are invalid/valid, to make sure that this doesn't randomly happen, and confuse users.
