### ISSUE TITLE
Maps reviews retrieval is failing

### ISSUE THREAD

**Issue by micduffy** [mxrch/GHunt#526]
**Describe the bug**

**To Reproduce**
1. Install and configure latest Ghunt
2. run an email analysis
3. See error

**Expected behavior**
Expecting it to run to completion

**Screenshots**
🎮 Play Games data

[-] No player profile found.

🗺️ Maps data
Traceback (most recent call last):
  File "/home/mike/.local/bin/ghunt", line 8, in <module>
    sys.exit(main())
  File "/home/mike/.local/lib/python3.10/site-packages/ghunt/ghunt.py", line 18, in main
    parse_and_run()
  File "/home/mike/.local/lib/python3.10/site-packages/ghunt/cli.py", line 55, in parse_and_run
    process_args(args)
  File "/home/mike/.local/lib/python3.10/site-packages/ghunt/cli.py", line 65, in process_args
    asyncio.run(email.hunt(None, args.email_address, args.json))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/mike/.local/lib/python3.10/site-packages/ghunt/modules/email.py", line 117, in hunt
    err, stats, reviews, photos = await gmaps.get_reviews(as_client, target.personId)
  File "/home/mike/.local/lib/python3.10/site-packages/ghunt/helpers/gmaps.py", line 56, in get_reviews
    data = json.loads(req.text[5:])
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**System (please complete the following information):**
 - OS
 - Python version

**Additional context**
Seems to be related to the get_reviews call - perhaps the url has changed ? It currently returns a 302 return code.

**Comment by Navitas28** [comment]
Yes similar issue here 
![Screenshot 2024-09-07 at 16 45 43](https://github.com/user-attachments/assets/a73c2955-5771-4f92-8da3-ebee68bf9c97)


The retrieval at line 56 of `gmaps.py` returns `status_code = 302` so the URL has changed

**Comment by micduffy** [comment]
I dont think this is an easy fix, as I go to https://www.google.com/maps/contrib/XYZ/reviews

where XYZ is a GAIA id. This firstly CAPTCHAS me but even after that, all reviews data is transferred in what appears to be a binary format - perhaps WASM blobs.

The above, coupled with locationhistory being removed from web channels makes be believe that there may not be a fix for this.

**Comment by micduffy** [comment]
So I found out that the retrieval fails on calculating the cost statistics so I changed line 333 of gmaps.py from 

            costs_stats[review.location.cost_level] += 1
to
            costs_stats[1] += 1

As I dont need the cost analysis for my purposes, then I just bypassed it.

Most likely the location.cost or location.cost_level has changed.

Hope this helps

**Comment by pegaggio** [comment]
This did not fix it for me, I still got the same error mentioned in the original post. However, I did try the url that ghunt attempted on an older, much more used account (completely separate from my ghunt only account) and it did work. I believe the problem is the same as the "KeyError: 'people'" one. Google looking at various statistics of an account and rate-limiting it based on the calculated legitimacy.
