### ISSUE TITLE
KeyError: 7

### ISSUE THREAD

**Issue by diehard88** [mxrch/GHunt#527]
I did a gmail login --clean, to no avail.

`
Traceback (most recent call last):
  File "/root/.local/bin/ghunt", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/ghunt/ghunt.py", line 18, in main
    parse_and_run()
  File "/usr/local/lib/python3.10/dist-packages/ghunt/cli.py", line 55, in parse_and_run
    process_args(args)
  File "/usr/local/lib/python3.10/dist-packages/ghunt/cli.py", line 65, in process_args
    asyncio.run(email.hunt(None, args.email_address, args.json))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.10/dist-packages/ghunt/modules/email.py", line 118, in hunt
    gmaps.output(err, stats, reviews, photos, target.personId)
  File "/usr/local/lib/python3.10/dist-packages/ghunt/helpers/gmaps.py", line 333, in output
    costs_stats[review.location.cost_level] += 1
KeyError: 7
root@localhost:~#
`

**Comment by diehard88** [comment]
Traceback (most recent call last):
  File "/root/.local/bin/ghunt", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/ghunt/ghunt.py", line 18, in main
    parse_and_run()
  File "/usr/local/lib/python3.10/dist-packages/ghunt/cli.py", line 55, in parse_and_run
    process_args(args)
  File "/usr/local/lib/python3.10/dist-packages/ghunt/cli.py", line 65, in process_args
    asyncio.run(email.hunt(None, args.email_address, args.json))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.10/dist-packages/ghunt/modules/email.py", line 118, in hunt
    gmaps.output(err, stats, reviews, photos, target.personId)
  File "/usr/local/lib/python3.10/dist-packages/ghunt/helpers/gmaps.py", line 333, in output
    costs_stats[review.location.cost_level] += 1
KeyError: 7
root@localhost:~#

**Comment by mxrch** [comment]
Related to https://github.com/mxrch/GHunt/issues/527
I'm closing this issue as the other is more popular
