### ISSUE TITLE
GHunt python3 error possibly easy fix for the writer?

### ISSUE THREAD

**Issue by ChillVibesMushroom** [mxrch/GHunt#530]
**Describe the bug**
It works at the beginning of the osint process but then out of no where an error occurs when it comes to reviews

**To Reproduce**
1. source venv/bin/activate
2.ghunt email test@gmail.com
3. works we see reviews 
4. try again same email or different email 
5. Here is the error 

Traceback (most recent call last):
  File "/home/h4t4moto/.local/bin/ghunt", line 8, in <module>
    sys.exit(main())
  File "/home/h4t4moto/.local/share/pipx/venvs/ghunt/lib/python3.10/site-packages/ghunt/ghunt.py", line 18, in main
    parse_and_run()
  File "/home/h4t4moto/.local/share/pipx/venvs/ghunt/lib/python3.10/site-packages/ghunt/cli.py", line 55, in parse_and_run
    process_args(args)
  File "/home/h4t4moto/.local/share/pipx/venvs/ghunt/lib/python3.10/site-packages/ghunt/cli.py", line 65, in process_args
    asyncio.run(email.hunt(None, args.email_address, args.json))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/h4t4moto/.local/share/pipx/venvs/ghunt/lib/python3.10/site-packages/ghunt/modules/email.py", line 117, in hunt
    err, stats, reviews, photos = await gmaps.get_reviews(as_client, target.personId)
  File "/home/h4t4moto/.local/share/pipx/venvs/ghunt/lib/python3.10/site-packages/ghunt/helpers/gmaps.py", line 56, in get_reviews
    data = json.loads(req.text[5:])
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Expected behavior**
Ghunt should work normally and show us the given reviews 

**Screenshots**

**System (please complete the following information):**
 - OS
 - Linux user 6.8.0-45-generic #45~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Sep 11 15:25:05 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

 - Python version
 - Python 3.10.12

**Additional context**
I enjoyed this tool a lot is it still actively maintained is this an easy fix I even disabled firewalls and still got the same results?

**Comment by ChillVibesMushroom** [comment]
This is what AI throws our way maybe we need an update if you have the time?


Possible Reasons for the Error

    Empty Response: The API might not be returning any data, possibly due to an invalid request or a rate limit being hit.
    Invalid URL or Endpoint: The URL you are trying to access might be incorrect.
    Network Issues: There may be connectivity issues preventing a proper response from the API.
    API Changes: The API might have changed its response format or might be down temporarily.

**Comment by mxrch** [comment]
Related to https://github.com/mxrch/GHunt/issues/529.
Please avoid AI answers as they provide no useful information.
