### ISSUE TITLE
Seleniumwire fail in proxy?

### ISSUE THREAD

**Issue by enclude** [mxrch/GHunt#70]
When run `sudo python3 hunt.py *@gmail.com` or `python3 hunt.py *@gmail.com` i got error after "Google Photos : https:// "

`Error making requestPhotos albums overview...   
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/seleniumwire/proxy/proxy2.py", line 91, in proxy_request
    conn.request(self.command, path, req_body, dict(req.headers))
  File "/usr/lib/python3.8/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1010, in _send_output
    self.send(msg)
  File "/usr/lib/python3.8/http/client.py", line 950, in send
    self.connect()
  File "/usr/local/lib/python3.8/dist-packages/seleniumwire/proxy/proxy2.py", line 368, in connect
    super().connect()
  File "/usr/lib/python3.8/http/client.py", line 1417, in connect
    super().connect()
  File "/usr/lib/python3.8/http/client.py", line 921, in connect
    self.sock = self._create_connection(
  File "/usr/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
^CTraceback (most recent call last):            
  File "hunt.py", line 119, in <module>
    gpics(gaiaID, client, cookies, cfg)
  File "/home/ubuntu/GHunt/lib/photos.py", line 105, in gpics
    results = re.compile(cfg["regexs"]["albums"]).findall(out["source"])
KeyboardInterrupt`

My OS:
`user@srv:~/GHunt$ uname -a
Linux srv 5.4.0-48-generic #52-Ubuntu SMP Thu Sep 10 9:58:49 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by tddschn** [comment]
proxy2.py in seleniumwire failed on my machine too (macOS, python 3.8)
![image](https://user-images.githubusercontent.com/45612704/95466946-7c0bb180-09af-11eb-908a-d24b7b256962.png)

![image](https://user-images.githubusercontent.com/45612704/95466896-6d24ff00-09af-11eb-8dd8-a70647229e2a.png)

**Comment by mxrch** [comment]
@enclude I think you just timed out with the regex, but since we don't use this part of the code I close this issue.
