### ISSUE TITLE
No module named 'sniffio'

### ISSUE THREAD

**Issue by shanow7** [mxrch/GHunt#74]
hi, I've problem, can you help?

python3 hunt.py -h
Traceback (most recent call last):
  File "hunt.py", line 7, in <module>
    import httpx
  File "/usr/local/lib/python3.8/dist-packages/httpx/__init__.py", line 2, in <module>
    from ._api import delete, get, head, options, patch, post, put, request, stream
  File "/usr/local/lib/python3.8/dist-packages/httpx/_api.py", line 3, in <module>
    from ._client import Client, StreamContextManager
  File "/usr/local/lib/python3.8/dist-packages/httpx/_client.py", line 7, in <module>
    import httpcore
  File "/usr/local/lib/python3.8/dist-packages/httpcore/__init__.py", line 2, in <module>
    from ._async.connection_pool import AsyncConnectionPool
  File "/usr/local/lib/python3.8/dist-packages/httpcore/_async/connection_pool.py", line 5, in <module>
    from .._backends.auto import AsyncLock, AsyncSemaphore
  File "/usr/local/lib/python3.8/dist-packages/httpcore/_backends/auto.py", line 4, in <module>
    import sniffio
ModuleNotFoundError: No module named 'sniffio'

**Comment by jantjeu** [comment]
it's mean you don't have httpx, httpcore, sniffio installed but first try 'python' not 'python3':

$ python hunt.py -h

**Comment by shanow7** [comment]
sudo pip install sniffio
[sudo] password for osint: 
Requirement already satisfied: sniffio in /root/.local/lib/python3.8/site-packages (1.1.0)
osint@kali:~/GHunt$ sudo pip install httpx
Requirement already satisfied: httpx in /usr/local/lib/python3.8/dist-packages (0.16.1)
Requirement already satisfied: httpcore==0.12.* in /usr/local/lib/python3.8/dist-packages (from httpx) (0.12.0)
Requirement already satisfied: rfc3986[idna2008]<2,>=1.3 in /root/.local/lib/python3.8/site-packages (from httpx) (1.4.0)
Requirement already satisfied: sniffio in /root/.local/lib/python3.8/site-packages (from httpx) (1.1.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.8/dist-packages (from httpx) (2020.6.20)
Requirement already satisfied: h11==0.* in /usr/local/lib/python3.8/dist-packages (from httpcore==0.12.*->httpx) (0.11.0)
Requirement already satisfied: idna; extra == "idna2008" in /usr/local/lib/python3.8/dist-packages (from rfc3986[idna2008]<2,>=1.3->httpx) (2.10)
osint@kali:~/GHunt$ sudo pip install httpcore
Requirement already satisfied: httpcore in /usr/local/lib/python3.8/dist-packages (0.12.0)
Requirement already satisfied: h11==0.* in /usr/local/lib/python3.8/dist-packages (from httpcore) (0.11.0)
Requirement already satisfied: sniffio==1.* in /root/.local/lib/python3.8/site-packages (from httpcore) (1.1.0)
osint@kali:~/GHunt$ python hunt.py -h
Traceback (most recent call last):
  File "hunt.py", line 7, in <module>
    import httpx
  File "/usr/local/lib/python3.8/dist-packages/httpx/__init__.py", line 2, in <module>
    from ._api import delete, get, head, options, patch, post, put, request, stream
  File "/usr/local/lib/python3.8/dist-packages/httpx/_api.py", line 3, in <module>
    from ._client import Client, StreamContextManager
  File "/usr/local/lib/python3.8/dist-packages/httpx/_client.py", line 7, in <module>
    import httpcore
  File "/usr/local/lib/python3.8/dist-packages/httpcore/__init__.py", line 2, in <module>
    from ._async.connection_pool import AsyncConnectionPool
  File "/usr/local/lib/python3.8/dist-packages/httpcore/_async/connection_pool.py", line 5, in <module>
    from .._backends.auto import AsyncLock, AsyncSemaphore
  File "/usr/local/lib/python3.8/dist-packages/httpcore/_backends/auto.py", line 4, in <module>
    import sniffio
ModuleNotFoundError: No module named 'sniffio'

**Comment by outime** [comment]
This is more related to Python support than GHunt IMHO. You could create a virtualenv and see if it works that way. Or the easiest way if you aren't familiar with these things is to just use the Docker version as it manages everything for you.

**Comment by mxrch** [comment]
@shanow7 try reinstalling the requirements.txt with "--user" option for pip.
Often installing the modules as sudo and run the python script as user works but I think in certain configurations it's not.
If it doesn't work, try also running the hunt.py as root just for the debug.

**Comment by shanow7** [comment]
it's workt it, but how can I generate cookies and tokens ?

**Comment by mxrch** [comment]
Just do "python3 check_and_gen.py" as written in the Readme.

**Comment by shanow7** [comment]
I do not understand this... "you will be asked for the 4 required cookies"
