### ISSUE TITLE
[+] The cookies seems valid ! Generating the Google Docs and Hangouts token...

### ISSUE THREAD

**Issue by presmedia002** [mxrch/GHunt#91]
[+] The cookies seems valid ! Generating the Google Docs and Hangouts token...

Google Docs Token => AC4w5Vhf1Qw6SfuT1VNZgQMa1k_DIdam5w:1602658865137
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/selenium/webdriver/common/service.py", line 72, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: './chromedriver'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "check_and_gen.py", line 74, in <module>
    driver = webdriver.Chrome(executable_path=driverpath, seleniumwire_options=options, options=chrome_options)
  File "/usr/local/lib/python3.8/dist-packages/seleniumwire/webdriver/browser.py", line 86, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/chrome/webdriver.py", line 92, in __init__
    self.service.start()
  File "/usr/lib/python3/dist-packages/selenium/webdriver/common/service.py", line 86, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable may have wrong permissions. Please see https://sites.google.com/a/chromium.org/chromedriver/home

**Comment by presmedia002** [comment]
got it ..please close it
