### ISSUE TITLE
PermissionError when running check_and_gen.py

### ISSUE THREAD

**Issue by dkasak** [mxrch/GHunt#94]
I made a virtualenv, activated it and installed GHunt's depedencies using

    pip install -r requirements.txt

Then I ran `python check_and_gen.py`. After entering the required cookies, it reports they seem valid and then the following happens:

    Traceback (most recent call last):
    File "/home/dkasak/code/projects/GHunt/venv/lib/python3.8/site-packages/selenium/webdriver/common/service.py", line 72, in start
        self.process = subprocess.Popen(cmd, env=self.env,
    File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
        self._execute_child(args, executable, preexec_fn, close_fds,
    File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    PermissionError: [Errno 13] Permission denied: '/home/dkasak/code/projects/GHunt/venv/lib/python3.8/site-packages/chromedriver_autoinstaller-0.2.2.dist-info'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
    File "scripts/check_and_gen.py", line 78, in <module>
        driver = webdriver.Chrome(executable_path=driverpath, seleniumwire_options=options, options=chrome_options)
    File "/home/dkasak/code/projects/GHunt/venv/lib/python3.8/site-packages/seleniumwire/webdriver/browser.py", line 86, in __init__
        super().__init__(*args, **kwargs)
    File "/home/dkasak/code/projects/GHunt/venv/lib/python3.8/site-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
        self.service.start()
    File "/home/dkasak/code/projects/GHunt/venv/lib/python3.8/site-packages/selenium/webdriver/common/service.py", line 86, in start
        raise WebDriverException(
    selenium.common.exceptions.WebDriverException: Message: 'chromedriver_autoinstaller-0.2.2.dist-info' executable may have wrong permissions. Please see https://sites.google.com/a/chromium.org/chromedriver/home

**Comment by pi-eaterVZ** [comment]
I have the same issue , venv , command prompt as admin (windows) 

PermissionError: [WinError 5] Toegang geweigerd
During handling of the above exception, another exception occurred:

  raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'chromedriver_autoinstaller' executable may have wrong permissions. Please see https://sites.google.com/a/chromium.org/chromedriver/home

**Comment by NikolozCh** [comment]
Hey guys.

Do you have **chromedriver** in the same folder as well as `hunt.py`?

if not, please go to Chrome Setting's page -> `chrome://version` (paste this as URL in Google Chrome), check your chrome version and go to Google [ChromeDriver Download Page](https://chromedriver.chromium.org/downloads). Then download related chromedriver and put that into the GHunt directory.

I hope it helps! (If not, I have no clue what should be wrong... maybe just permissions? try `ls -la` and `whoami` in order to check permissions in bash)
